// TEST-SPEC §7.4–7.5 (coverage profiles, policy rules) — SUITE-29: T7.4-1,
// T7.4-2, T7.5-1…T7.5-6. Configuration basics (T7-1…T7-3) live in
// section-7-basics.ts, discovery (T7-4…T7-6) in section-7-discovery.ts, and
// §7.1–7.3 in section-7.1-7.3.ts; the section-8 coverage tests (T8-*,
// T8.2-1) own the full coverage-report contract and belong to SUITE-30.
//
// Registered product-facing bodies (C-2 "one code path"): each builds its own
// fresh workspace (H-1), drives the product strictly as a subprocess (H-2),
// asserts exact exit codes (H-5), decodes reports through the H-3 adapters,
// and rejects a product only via diagnosed assertion failures (H-8).
//
// SPEC 7.4: coverage profiles carry `name` (unique), `target` (a configured
// spec group's name), optional `targetTags` (non-empty), `targets`
// ("leaves" default | "all"), `boundary` (spec or code group), `boundaryKind`
// ("spec" | "code" — inferred when the name is unambiguous, required when it
// names both a spec and a code group), `mode` ("direct" | "transitive"), and
// optional `edgeKinds` (non-empty subset of the three dependency kinds,
// defaulting to all three). SPEC 7.5: policy rules carry `name` (unique),
// `type` ("forbidden" | "allowedOnly"), `from`/`to` selectors (exactly one of
// group/files/tags; group optionally kind-qualified like boundaryKind), and
// optional `kinds`; `files` selectors support capture wildcards `$1`…`$9`
// (each at most once in `from`; a `to` capture must exist in `from`; a
// capture takes one or more bytes within a single segment, shortest-match
// left to right). Violations are findings of `check` — and only `check`
// (14.12): `build` does not evaluate policy (12.1).
//
// Conservative operationalizations (noted per H-3/H-4):
// - 14.14 contract: `expectConfigurationError` (shared, ./support.ts) — exit
//   2 exactly, byte-empty stdout under --json, stderr matching /config/i.
//   Every invalid fixture stages valid sources for every configured group, so
//   the staged deviation is the workspace's only defect: a product that
//   wrongly accepts the configuration proceeds to a clean build (exit 0) and
//   fails the exit-code assertion — never exits 2 for a side reason.
// - Unknown profile name at `coverage <name>` (T7.4-1) is a 12.0 usage error,
//   not a 14.14: asserted as exit 2 with byte-empty stdout under --json (the
//   exit-2 error prevents emitting the single JSON document, H-5) and a
//   non-empty stderr diagnostic — no /config/i duty applies.
// - Policy findings are compared as sorted "rule :: kind: from -> to"
//   renderings plus an exact 14.12 condition count: SPEC 7.5 fixes the
//   information (rule name + offending edge) and one finding per (rule, edge)
//   pair, not an order or a location (the edge is the subject, not a source
//   span).
// - Every `check` run is preceded by a successful `build` in the same
//   workspace, so generated output is fresh and the policy findings are the
//   run's only findings (no 14.10 staleness contamination) — the exact
//   condition count then has teeth.
// - T7.4-2 asserts required-set composition through covered/uncovered
//   membership (required = covered ∪ uncovered, 8.1) and pins the single
//   possible covering path for spec-boundary profiles; the code-boundary
//   profile asserts membership only — code-location attribution and
//   code-boundary path shape are T8-3/T4.6's subjects. Counts, ignored-node
//   composition, and report ordering are T8.2-1's subject, so profiles are
//   looked up by name and row sets compared sorted.
// - T7.5-5 capture VALUES are observed through `to`-expansion agreement (the
//   only black-box channel SPEC 7.5 defines): each fixture stages one target
//   per plausible-but-wrong disambiguation (greedy capture, greedy leading
//   `*`, whole-path regex) so the exact finding set pins the captured tuple.
//   Determinism of the shortest-match disambiguation runs the identical
//   `check --json` twice and asserts byte-identical outputs (H-6).
// - T7.5-6 "regenerates output" is asserted by tampering with a generated
//   module after a first build and byte-comparing it back after a rebuild —
//   a product-to-itself comparison (H-4 allows those; 12.0 makes the
//   regenerated bytes deterministic). "Only check reports them" is asserted
//   as build exiting 0 (a reported policy finding causes exit 1, 7.5) while
//   the same workspace's check exits 1 with exactly the staged findings.

import type {
  CoverageProfileReport,
  CoverageReport,
  Finding,
  GraphEdge,
} from "../../helpers/adapters/index.js";
import {
  decodeCoverageReport,
  decodeFindingsReport,
} from "../../helpers/adapters/index.js";
import {
  assertFileBytes,
  assertStdoutEmpty,
  fail,
  parseJsonStdout,
} from "../../helpers/assertions.js";
import { assertRunTwiceDeterministic } from "../../helpers/determinism.js";
import { defineProductTest } from "../../helpers/registry.js";
import type { ProductTestEntry } from "../../helpers/registry.js";
import type { ProductBinding } from "../../helpers/subprocess.js";
import { summarizeResult } from "../../helpers/subprocess.js";
import { TestWorkspace } from "../../helpers/workspace.js";
import type { WorkspaceDecl } from "../../helpers/workspace.js";
import {
  assertConditionCounts,
  assertSameJson,
  buildOk,
  expectConfigurationError,
  expectExit,
  readGeneratedModule,
  runJson,
  sortedIdentities,
} from "./support.js";

// ---------------------------------------------------------------------------
// Shared fixture material
// ---------------------------------------------------------------------------

/** A minimal valid single-section source: one node `<id>` under the root. */
function mdxSection(id: string): string {
  return `<S id="${id}">\nText for ${id}.\n</S>\n`;
}

/** Stage a fresh workspace, run `body`, dispose (H-1). */
async function withWorkspace<T>(
  decl: WorkspaceDecl,
  body: (workspace: TestWorkspace) => Promise<T>,
): Promise<T> {
  const workspace = await TestWorkspace.create(decl);
  try {
    return await body(workspace);
  } finally {
    await workspace.dispose();
  }
}

/**
 * Stage a workspace with the given configuration and source files and assert
 * `build --json` refuses it per 14.14 (module header: the deviation is the
 * only defect, so wrong acceptance surfaces as a failed exit-code assertion).
 */
async function expectConfigRefused(
  product: ProductBinding,
  config: string,
  files: Readonly<Record<string, string>>,
  context: string,
): Promise<void> {
  await withWorkspace(
    { files: { "xspec.config.ts": config, ...files } },
    async (workspace) => {
      await expectConfigurationError(product, workspace, ["build"], context);
    },
  );
}

/**
 * Render one `coverage`/`policy` entry list as configuration text: each entry
 * is a list of raw field lines, so every matrix arm states its full literal
 * and the single deviation is visible in the arm itself.
 */
function entriesBlock(
  key: "coverage" | "policy",
  entries: readonly (readonly string[])[],
): string {
  const rendered = entries
    .map(
      (fields) =>
        `    {\n${fields.map((field) => `      ${field}`).join(",\n")}\n    }`,
    )
    .join(",\n");
  return `  ${key}: [\n${rendered}\n  ]`;
}

// The validation-matrix group layout (T7.4-1, T7.5-1): two spec groups (so
// group-typed references have a valid unambiguous referent and a second
// distinct group), one code group (for the wrong-kind arms). Every group
// holds one valid staged source (MATRIX_FILES).
const MATRIX_GROUPS = `  specs: {
    main: ["specs/**/*.mdx"],
    aux: ["aux/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  }`;

function matrixConfig(block: string): string {
  return `import { defineConfig } from "xspec"

export default defineConfig({
${MATRIX_GROUPS},
${block}
})
`;
}

const MATRIX_FILES: Readonly<Record<string, string>> = {
  "specs/A.mdx": mdxSection("a"),
  "aux/X.mdx": mdxSection("x"),
  "src/impl.ts": "export const ok = 1;\n",
};

// The ambiguous-name layout: `dual` exists as both a spec group and a code
// group (distinct maps, disjoint globs — no 14.14 file overlap), so a bare
// reference to `dual` is ambiguous (SPEC 7.4, 7.5).
const DUAL_GROUPS = `  specs: {
    main: ["specs/**/*.mdx"],
    dual: ["dualspec/**/*.mdx"]
  },
  code: {
    dual: ["dualcode/**/*.ts"]
  }`;

function dualConfig(block: string): string {
  return `import { defineConfig } from "xspec"

export default defineConfig({
${DUAL_GROUPS},
${block}
})
`;
}

const DUAL_FILES: Readonly<Record<string, string>> = {
  "specs/A.mdx": mdxSection("a"),
  "dualspec/D.mdx": mdxSection("d"),
  "dualcode/d.ts": "export const ok = 1;\n",
};

/**
 * Run `check --json` expecting findings (exit 1, one JSON document as the
 * entire stdout, H-5) and return the decoded findings (H-3).
 */
async function checkFindings(
  product: ProductBinding,
  workspace: TestWorkspace,
  context: string,
): Promise<readonly Finding[]> {
  const result = await expectExit(
    product,
    workspace,
    ["check", "--json"],
    1,
    `${context} — policy violations are findings of check and cause exit 1 ` +
      `(SPEC 7.5, 14.12, 12.0)`,
  );
  return decodeFindingsReport(parseJsonStdout(result, context), context)
    .findings;
}

/** One expected policy finding: the rule name plus the offending edge. */
interface PolicyExpectation {
  readonly rule: string;
  readonly edge: GraphEdge;
}

function renderPolicyPair(rule: string, edge: GraphEdge): string {
  return `${rule} :: ${edge.kind}: ${edge.from} -> ${edge.to}`;
}

/**
 * Assert a findings report carries exactly the expected policy findings: the
 * condition multiset is exactly `14.12 × n` (nothing masked, nothing phantom)
 * and the (rule, offending edge) pairs match, order-insensitively (module
 * header: SPEC 7.5 fixes the information, not an order).
 */
function assertPolicyFindings(
  findings: readonly Finding[],
  expected: readonly PolicyExpectation[],
  context: string,
): void {
  assertConditionCounts(
    findings,
    expected.length === 0 ? {} : { "14.12": expected.length },
    context,
  );
  // SPEC 14.12/12.7: the offending entity is a graph edge, not a spelling —
  // `locations` empty, `path` null, the identities in order the violated
  // rule's name and the edge's source identity, kind token, and target.
  for (const finding of findings) {
    if (finding.locations.length !== 0 || finding.path !== null) {
      fail(
        `${context}: a policy finding carries no in-source locations and ` +
          `concerns no path — \`locations\` [], \`path\` null (SPEC 14.12, ` +
          `12.7); got locations ${JSON.stringify(finding.locations)}, path ` +
          `${JSON.stringify(finding.path)}`,
      );
    }
  }
  assertSameJson(
    findings
      .map((finding) => {
        if (finding.identities.length !== 4) {
          return `<malformed 14.12 identities> ${JSON.stringify(finding.identities)}`;
        }
        const [rule, from, kind, to] = finding.identities;
        return `${rule} :: ${kind}: ${from} -> ${to}`;
      })
      .sort(),
    expected.map((entry) => renderPolicyPair(entry.rule, entry.edge)).sort(),
    `${context}: policy findings' identities as (rule name, offending edge) ` +
      `pairs (SPEC 7.5, 14.12, 12.7)`,
  );
}

/**
 * The staged-policy protocol (module header): `build` must succeed — sources
 * are valid and policy never fails a build (12.1) — so the following `check`
 * runs over fresh generated output and its findings are exactly the staged
 * policy violations.
 */
async function expectPolicyFindings(
  product: ProductBinding,
  files: Readonly<Record<string, string>>,
  expected: readonly PolicyExpectation[],
  contextBase: string,
): Promise<void> {
  await withWorkspace({ files }, async (workspace) => {
    await buildOk(
      product,
      workspace,
      `${contextBase} \`build\` — sources are valid and build does not ` +
        `evaluate policy (SPEC 12.1, 7.5), so the check below observes ` +
        `fresh output and only policy findings`,
    );
    const label = `${contextBase} \`check --json\``;
    assertPolicyFindings(
      await checkFindings(product, workspace, label),
      expected,
      label,
    );
  });
}

/** Resolve one profile of a coverage report by name, diagnosed (H-8). */
function profileNamed(
  report: CoverageReport,
  name: string,
  context: string,
): CoverageProfileReport {
  const profile = report.profiles.find((candidate) => candidate.name === name);
  if (profile === undefined) {
    fail(
      `${context}: the coverage report must carry profile ${JSON.stringify(name)} — ` +
        `all configured profiles run by default (SPEC 8.2); got profiles ` +
        `${JSON.stringify(report.profiles.map((candidate) => candidate.name))}`,
    );
  }
  return profile;
}

// ---------------------------------------------------------------------------
// T7.4-1 — profile validation
// ---------------------------------------------------------------------------

// Each arm is the valid profile { name: "p", target: "main", boundary: "aux",
// mode: "direct" } with exactly one deviation, stated in full (module
// header). All are 14.14 → exit 2.
const PROFILE_MATRIX: readonly {
  readonly label: string;
  readonly profiles: readonly (readonly string[])[];
}[] = [
  {
    label:
      "two profiles sharing a name (distinct in mode, so the collision is " +
      "the name alone)",
    profiles: [
      ['name: "p"', 'target: "main"', 'boundary: "aux"', 'mode: "direct"'],
      ['name: "p"', 'target: "main"', 'boundary: "aux"', 'mode: "transitive"'],
    ],
  },
  {
    label: "profile lacking required `name`",
    profiles: [['target: "main"', 'boundary: "aux"', 'mode: "direct"']],
  },
  {
    label: "profile lacking required `target`",
    profiles: [['name: "p"', 'boundary: "aux"', 'mode: "direct"']],
  },
  {
    label: "profile lacking required `boundary`",
    profiles: [['name: "p"', 'target: "main"', 'mode: "direct"']],
  },
  {
    label: "profile lacking required `mode`",
    profiles: [['name: "p"', 'target: "main"', 'boundary: "aux"']],
  },
  {
    label: '`targets` other than "leaves"/"all"',
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        'targets: "roots"',
        'boundary: "aux"',
        'mode: "direct"',
      ],
    ],
  },
  {
    label: '`mode` other than "direct"/"transitive"',
    profiles: [
      ['name: "p"', 'target: "main"', 'boundary: "aux"', 'mode: "indirect"'],
    ],
  },
  {
    label: '`boundaryKind` other than "spec"/"code"',
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        'boundary: "aux"',
        'boundaryKind: "group"',
        'mode: "direct"',
      ],
    ],
  },
  {
    label: "unknown `target` group name",
    profiles: [
      ['name: "p"', 'target: "nope"', 'boundary: "aux"', 'mode: "direct"'],
    ],
  },
  {
    label:
      "`target` naming an existing code-only group (app) — the wrong-kind " +
      "reference of 14.14: target must be a configured spec group's name " +
      "(7.4), discriminating against validation over all group names",
    profiles: [
      ['name: "p"', 'target: "app"', 'boundary: "aux"', 'mode: "direct"'],
    ],
  },
  {
    label: "unknown `boundary` group name",
    profiles: [
      ['name: "p"', 'target: "main"', 'boundary: "nope"', 'mode: "direct"'],
    ],
  },
  {
    label:
      '`boundaryKind: "spec"` naming the code-only group app (the referenced ' +
      "name is not of the required kind)",
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        'boundary: "app"',
        'boundaryKind: "spec"',
        'mode: "direct"',
      ],
    ],
  },
  {
    label:
      '`boundaryKind: "code"` naming the spec-only group aux (the other ' +
      "direction of the wrong-kind reference)",
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        'boundary: "aux"',
        'boundaryKind: "code"',
        'mode: "direct"',
      ],
    ],
  },
  {
    label: "empty `targetTags` list",
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        "targetTags: []",
        'boundary: "aux"',
        'mode: "direct"',
      ],
    ],
  },
  {
    label: "empty `edgeKinds` list",
    profiles: [
      [
        'name: "p"',
        'target: "main"',
        'boundary: "aux"',
        'mode: "direct"',
        "edgeKinds: []",
      ],
    ],
  },
];

// `boundary: "dual"` where dual is both a spec and a code group, boundaryKind
// absent → 14.14 (7.4: boundaryKind MUST be required when ambiguous).
const AMBIGUOUS_BOUNDARY_ABSENT_CONFIG = dualConfig(
  entriesBlock("coverage", [
    ['name: "p"', 'target: "main"', 'boundary: "dual"', 'mode: "direct"'],
  ]),
);

// The same ambiguous name with boundaryKind given, both directions → valid.
const AMBIGUOUS_BOUNDARY_GIVEN_CONFIG = dualConfig(
  entriesBlock("coverage", [
    [
      'name: "p-spec"',
      'target: "main"',
      'boundary: "dual"',
      'boundaryKind: "spec"',
      'mode: "direct"',
    ],
    [
      'name: "p-code"',
      'target: "main"',
      'boundary: "dual"',
      'boundaryKind: "code"',
      'mode: "direct"',
    ],
  ]),
);

// Unambiguous boundary names without boundaryKind — one spec-only (aux), one
// code-only (app) → valid: the kind MUST be inferred (7.4).
const INFERRED_KIND_CONFIG = matrixConfig(
  entriesBlock("coverage", [
    ['name: "p-spec"', 'target: "main"', 'boundary: "aux"', 'mode: "direct"'],
    ['name: "p-code"', 'target: "main"', 'boundary: "app"', 'mode: "direct"'],
  ]),
);

// One valid profile, for the unknown-profile-name usage-error arm.
const VALID_COVERAGE_CONFIG = matrixConfig(
  entriesBlock("coverage", [
    ['name: "p"', 'target: "main"', 'boundary: "aux"', 'mode: "direct"'],
  ]),
);

const T7_4_1 = defineProductTest({
  id: "T7.4-1",
  title:
    "profile validation: duplicate names, each missing required field, " +
    "invalid targets/mode/boundaryKind values, unknown and wrong-kind " +
    "target/boundary references, empty targetTags/edgeKinds, and an " +
    "ambiguous boundary without boundaryKind are configuration errors " +
    "(14.14, exit 2); boundaryKind is inferred when unambiguous; an unknown " +
    "profile name at `coverage <name>` is a usage error (SPEC 7.4, 14.14, " +
    "12.0)",
  run: async (product) => {
    // (a) The 14.14 matrix over the standard group layout.
    for (const arm of PROFILE_MATRIX) {
      await expectConfigRefused(
        product,
        matrixConfig(entriesBlock("coverage", arm.profiles)),
        MATRIX_FILES,
        `T7.4-1 (${arm.label})`,
      );
    }

    // (b) boundaryKind required when the boundary name is both a spec and a
    // code group: absent → 14.14.
    await expectConfigRefused(
      product,
      AMBIGUOUS_BOUNDARY_ABSENT_CONFIG,
      DUAL_FILES,
      'T7.4-1 (`boundary: "dual"` naming both a spec and a code group, ' +
        "boundaryKind absent)",
    );

    // (c) The positive side: the ambiguous name with boundaryKind given
    // (either direction) is valid…
    await withWorkspace(
      {
        files: {
          "xspec.config.ts": AMBIGUOUS_BOUNDARY_GIVEN_CONFIG,
          ...DUAL_FILES,
        },
      },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T7.4-1 (ambiguous boundary name disambiguated by boundaryKind, " +
            "spec and code directions): `build` accepts the configuration " +
            "(SPEC 7.4)",
        );
      },
    );

    // …and boundaryKind MUST be inferred when the name is unambiguous: a
    // spec-only and a code-only boundary, neither carrying boundaryKind.
    await withWorkspace(
      { files: { "xspec.config.ts": INFERRED_KIND_CONFIG, ...MATRIX_FILES } },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T7.4-1 (unambiguous spec-only and code-only boundary names " +
            "without boundaryKind): `build` accepts the configuration — the " +
            "kind is inferred (SPEC 7.4)",
        );
      },
    );

    // (d) Unknown profile name at `coverage <name>` → usage error (12.0):
    // exit 2, byte-empty stdout under --json, a stderr diagnostic. Not a
    // 14.14 (the configuration is valid), so no /config/i duty applies.
    await withWorkspace(
      { files: { "xspec.config.ts": VALID_COVERAGE_CONFIG, ...MATRIX_FILES } },
      async (workspace) => {
        const label = "T7.4-1 `coverage nope --json` (unknown profile name)";
        const result = await expectExit(
          product,
          workspace,
          ["coverage", "nope", "--json"],
          2,
          `${label} — an unknown profile named in arguments is a usage ` +
            `error (SPEC 12.0)`,
        );
        assertStdoutEmpty(
          result,
          `${label} — under --json, stdout is byte-empty on exit 2: the ` +
            `usage error prevents emitting the single JSON document ` +
            `(SPEC 12.0, H-5)`,
        );
        if (result.stderrBytes.length === 0) {
          fail(
            `${label}: the usage error must be a standard-error diagnostic ` +
              `(SPEC 12.0); stderr is empty — ${summarizeResult(result)}`,
          );
        }
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T7.4-2 — profile semantics
// ---------------------------------------------------------------------------

// One workspace, five profiles differing in exactly one knob each. Graph
// (beyond contains edges):
//
//   bnd/B.mdx#dep  --depends-->     tgt/T.mdx#t.one   (d prop, 2.2)
//   bnd/B.mdx#emb  --embeds-->      tgt/T.mdx#t.two   ({text(...)}, 2.3)
//   bnd/B.mdx#int  --depends-->     tgt/T.mdx#t       (the internal node)
//   src/impl.ts    --references-->  tgt/T.mdx#t.two   (marker, 4.5/4.6)
//
// Target group `tgt` holds one internal node `t` with leaves `t.one` (tagged
// `hot`) and `t.two` (untagged). Boundary group `bnd` (spec, unambiguous —
// kind inferred) and code group `app` (the references-kind boundary). Every
// profile uses `direct` mode: T8-1/T8-2 own mode semantics.
const SEMANTICS_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    tgt: ["tgt/**/*.mdx"],
    bnd: ["bnd/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  },
  coverage: [
    {
      name: "p-default",
      target: "tgt",
      boundary: "bnd",
      mode: "direct"
    },
    {
      name: "p-all",
      target: "tgt",
      boundary: "bnd",
      targets: "all",
      mode: "direct"
    },
    {
      name: "p-tagged",
      target: "tgt",
      boundary: "bnd",
      targetTags: ["hot", "cold"],
      mode: "direct"
    },
    {
      name: "p-kinds",
      target: "tgt",
      boundary: "bnd",
      mode: "direct",
      edgeKinds: ["depends"]
    },
    {
      name: "p-code",
      target: "tgt",
      boundary: "app",
      mode: "direct"
    }
  ]
})
`;

const SEMANTICS_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": SEMANTICS_CONFIG,
  "tgt/T.mdx": `<S id="t">
Internal parent behavior.

<S id="t.one" tags="hot">
Leaf one behavior.
</S>

<S id="t.two">
Leaf two behavior.
</S>
</S>
`,
  "bnd/B.mdx": `import T from "../tgt/T.xspec"

<S id="dep" d={T.t.one}>
Depends on leaf one.
</S>

<S id="emb">
Embeds leaf two:

{text(T.t.two)}
</S>

<S id="int" d={T.t}>
Depends on the internal parent.
</S>
`,
  "src/impl.ts": `import T from "../tgt/T.xspec"

T.t.two
`,
};

const TGT_INTERNAL = "tgt/T.mdx#t";
const TGT_ONE = "tgt/T.mdx#t.one";
const TGT_TWO = "tgt/T.mdx#t.two";
const BND_DEP = "bnd/B.mdx#dep";
const BND_EMB = "bnd/B.mdx#emb";
const BND_INT = "bnd/B.mdx#int";

/** Covered rows as sorted {identity, path} pairs (each fixture path is the
 * single possible covering path, so no 12.0 tie-break is in play). */
function coveredWithPaths(
  profile: CoverageProfileReport,
): { identity: string; path: readonly string[] }[] {
  return profile.covered
    .map((node) => ({ identity: node.identity, path: node.path }))
    .sort((a, b) => (a.identity < b.identity ? -1 : 1));
}

const T7_4_2 = defineProductTest({
  id: "T7.4-2",
  title:
    "profile semantics via coverage runs: `targets` defaults to leaves, " +
    '"all" includes internal nodes, `targetTags` restricts to nodes ' +
    "carrying at least one listed tag, and `edgeKinds` defaults to all " +
    "three dependency kinds and restricts paths when given (SPEC 7.4, 8, " +
    "8.1)",
  run: async (product) => {
    await withWorkspace({ files: SEMANTICS_FILES }, async (workspace) => {
      await buildOk(
        product,
        workspace,
        "T7.4-2 `build` over the profile-semantics fixture",
      );
      const label = "T7.4-2 `coverage --json`";
      const report = decodeCoverageReport(
        await runJson(product, workspace, ["coverage", "--json"], label),
        label,
      );

      // p-default: `targets` omitted defaults to "leaves" — the required set
      // is exactly the two leaves; the internal node t (covered via int→t if
      // it were required) and the root appear nowhere in covered/uncovered.
      // Both leaves are covered under the default edgeKinds: t.one over a
      // depends edge, t.two over an embeds edge.
      const pDefault = profileNamed(report, "p-default", label);
      assertSameJson(
        coveredWithPaths(pDefault),
        [
          { identity: TGT_ONE, path: [BND_DEP, TGT_ONE] },
          { identity: TGT_TWO, path: [BND_EMB, TGT_TWO] },
        ],
        `${label} profile p-default: exactly the two leaves are covered — ` +
          `targets defaults to "leaves" (the internal node is not required, ` +
          `SPEC 7.4, 8.1), and the default edgeKinds admit both the depends ` +
          `and the embeds covering edge (SPEC 7.4, 8)`,
      );
      assertSameJson(
        [...pDefault.uncovered].sort(),
        [],
        `${label} profile p-default: no required node is uncovered ` +
          `(required = covered ∪ uncovered, SPEC 8.1/8.2)`,
      );

      // p-all: targets "all" adds the internal node to the required set
      // (roots stay excluded, 8.1); it is covered via the int→t edge.
      const pAll = profileNamed(report, "p-all", label);
      assertSameJson(
        coveredWithPaths(pAll),
        [
          { identity: TGT_INTERNAL, path: [BND_INT, TGT_INTERNAL] },
          { identity: TGT_ONE, path: [BND_DEP, TGT_ONE] },
          { identity: TGT_TWO, path: [BND_EMB, TGT_TWO] },
        ],
        `${label} profile p-all: targets "all" includes the internal node t ` +
          `in the required set — and never the root (SPEC 7.4, 8.1)`,
      );
      assertSameJson(
        [...pAll.uncovered].sort(),
        [],
        `${label} profile p-all: no required node is uncovered (SPEC 8.1)`,
      );

      // p-tagged: targetTags ["hot", "cold"] restricts the required set to
      // nodes carrying AT LEAST ONE listed tag — t.one carries hot (not
      // cold) and is required; the untagged t.two is not.
      const pTagged = profileNamed(report, "p-tagged", label);
      assertSameJson(
        coveredWithPaths(pTagged),
        [{ identity: TGT_ONE, path: [BND_DEP, TGT_ONE] }],
        `${label} profile p-tagged: only the hot-tagged leaf is required — ` +
          `targetTags restricts to nodes carrying at least one listed tag ` +
          `(t.one carries hot but not cold, so all-tags matching would ` +
          `exclude it; SPEC 7.4, 8.1)`,
      );
      assertSameJson(
        [...pTagged.uncovered].sort(),
        [],
        `${label} profile p-tagged: no required node is uncovered (SPEC 8.1)`,
      );

      // p-kinds: edgeKinds ["depends"] restricts covering paths — t.two's
      // only boundary edge is embeds, so it is uncovered although covered
      // under p-default's full default.
      const pKinds = profileNamed(report, "p-kinds", label);
      assertSameJson(
        coveredWithPaths(pKinds),
        [{ identity: TGT_ONE, path: [BND_DEP, TGT_ONE] }],
        `${label} profile p-kinds: only the depends-covered leaf remains ` +
          `covered under edgeKinds ["depends"] (SPEC 7.4, 8)`,
      );
      assertSameJson(
        [...pKinds.uncovered].sort(),
        [TGT_TWO],
        `${label} profile p-kinds: the embeds-covered leaf is uncovered — ` +
          `the given edgeKinds exclude its only covering path's kind ` +
          `(SPEC 7.4, 8)`,
      );

      // p-code: a code-group boundary under the DEFAULT edgeKinds — the
      // references edge from the marker covers t.two, completing "defaults
      // to all three" (depends and embeds are covered by p-default).
      // Membership only: code-location attribution and code-boundary path
      // shape are T8-3/T4.6's subjects (module header).
      const pCode = profileNamed(report, "p-code", label);
      assertSameJson(
        sortedIdentities(pCode.covered),
        [TGT_TWO],
        `${label} profile p-code: the marker's references edge covers t.two ` +
          `under the omitted edgeKinds — the default includes all three ` +
          `dependency kinds (SPEC 7.4, 8, 4.5)`,
      );
      assertSameJson(
        [...pCode.uncovered].sort(),
        [TGT_ONE],
        `${label} profile p-code: t.one has no edge from the code boundary ` +
          `and is uncovered (SPEC 8)`,
      );
    });
  },
});

// ---------------------------------------------------------------------------
// T7.5-1 — rule validation
// ---------------------------------------------------------------------------

// Each arm is the valid rule { name: "r", type: "forbidden", from: { group:
// "main" }, to: { group: "aux" } } with exactly one deviation. All are 14.14
// → exit 2.
const RULE_MATRIX: readonly {
  readonly label: string;
  readonly rules: readonly (readonly string[])[];
}[] = [
  {
    label:
      "two rules sharing a name (distinct in type, so the collision is the " +
      "name alone)",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "main" }',
        'to: { group: "aux" }',
      ],
      [
        'name: "r"',
        'type: "allowedOnly"',
        'from: { group: "main" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label: "rule lacking required `name`",
    rules: [
      ['type: "forbidden"', 'from: { group: "main" }', 'to: { group: "aux" }'],
    ],
  },
  {
    label: "rule lacking required `type`",
    rules: [['name: "r"', 'from: { group: "main" }', 'to: { group: "aux" }']],
  },
  {
    label: "rule lacking required `from`",
    rules: [['name: "r"', 'type: "forbidden"', 'to: { group: "aux" }']],
  },
  {
    label: "rule lacking required `to`",
    rules: [['name: "r"', 'type: "forbidden"', 'from: { group: "main" }']],
  },
  {
    label: '`type` other than "forbidden"/"allowedOnly"',
    rules: [
      [
        'name: "r"',
        'type: "banned"',
        'from: { group: "main" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label: "empty `kinds` list",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "main" }',
        'to: { group: "aux" }',
        "kinds: []",
      ],
    ],
  },
  {
    label: "empty selector `tags` list",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        "from: { tags: [] }",
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label: "selector with zero of group/files/tags",
    rules: [
      ['name: "r"', 'type: "forbidden"', "from: {}", 'to: { group: "aux" }'],
    ],
  },
  {
    label: "selector with two of group/files/tags",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "main", files: "specs/*.mdx" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label: "unknown group name in a selector",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "nope" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label:
      'selector `kind: "spec"` naming the code-only group app (kind ' +
      "mismatching the group's kind)",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "app", kind: "spec" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label:
      'selector `kind: "code"` naming the spec-only group main (the other ' +
      "direction)",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { group: "main", kind: "code" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label:
      "capture wildcard $1 appearing more than once in `from` (a capture " +
      "violation)",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { files: "specs/$1-$1.mdx" }',
        'to: { group: "aux" }',
      ],
    ],
  },
  {
    label: "`to` referencing capture $2 absent from `from`",
    rules: [
      [
        'name: "r"',
        'type: "forbidden"',
        'from: { files: "specs/$1.mdx" }',
        'to: { files: "aux/$2.mdx" }',
      ],
    ],
  },
];

// An ambiguous group name in a selector without `kind` → 14.14 (7.5: the
// kind MUST be given when the name exists as both a spec and a code group).
const AMBIGUOUS_SELECTOR_CONFIG = dualConfig(
  entriesBlock("policy", [
    [
      'name: "r"',
      'type: "forbidden"',
      'from: { group: "dual" }',
      'to: { group: "main" }',
    ],
  ]),
);

const T7_5_1 = defineProductTest({
  id: "T7.5-1",
  title:
    "rule validation: duplicate names, each missing required field, an " +
    "invalid type, empty kinds/tags lists, selectors with zero or two of " +
    "group/files/tags, unknown, wrong-kind, and ambiguous group references, " +
    "a capture used twice in `from`, and a `to` referencing an absent " +
    "capture are configuration errors (SPEC 7.5, 14.14, exit 2)",
  run: async (product) => {
    for (const arm of RULE_MATRIX) {
      await expectConfigRefused(
        product,
        matrixConfig(entriesBlock("policy", arm.rules)),
        MATRIX_FILES,
        `T7.5-1 (${arm.label})`,
      );
    }
    await expectConfigRefused(
      product,
      AMBIGUOUS_SELECTOR_CONFIG,
      DUAL_FILES,
      "T7.5-1 (selector naming the ambiguous group dual — both a spec and a " +
        "code group — without kind)",
    );
  },
});

// ---------------------------------------------------------------------------
// T7.5-2 — forbidden
// ---------------------------------------------------------------------------

// Matching semantics: three groups, three depends edges — only the edge
// matching BOTH `from` and `to` is a finding.
//
//   hi/H.mdx#bad    --depends--> lo/L.mdx#l    from ✓ to ✓  → finding
//   hi/H.mdx#ok     --depends--> mid/M.mdx#m   from ✓ to ✗  → none
//   mid/M.mdx#muses --depends--> lo/L.mdx#l    from ✗ to ✓  → none
const FORBIDDEN_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    hi: ["hi/**/*.mdx"],
    lo: ["lo/**/*.mdx"],
    mid: ["mid/**/*.mdx"]
  },
  policy: [
    {
      name: "no-hi-to-lo",
      type: "forbidden",
      from: { group: "hi" },
      to: { group: "lo" }
    }
  ]
})
`,
  "hi/H.mdx": `import L from "../lo/L.xspec"
import M from "../mid/M.xspec"

<S id="bad" d={L.l}>
Depends on the low group.
</S>

<S id="ok" d={M.m}>
Depends on the mid group.
</S>
`,
  "lo/L.mdx": mdxSection("l"),
  "mid/M.mdx": `import L from "../lo/L.xspec"

<S id="m">
Mid behavior.
</S>

<S id="muses" d={L.l}>
Mid uses the low group.
</S>
`,
};

// `kinds` restriction: one source node with a depends edge AND an embeds edge
// into the forbidden group; kinds ["embeds"] evaluates only the embeds edge.
const FORBIDDEN_KINDS_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    hi: ["hi/**/*.mdx"],
    lo: ["lo/**/*.mdx"]
  },
  policy: [
    {
      name: "no-embed",
      type: "forbidden",
      from: { group: "hi" },
      to: { group: "lo" },
      kinds: ["embeds"]
    }
  ]
})
`,
  "hi/H.mdx": `import L from "../lo/L.xspec"

<S id="has" d={L.l}>
Uses the low group, and embeds it:

{text(L.l2)}
</S>
`,
  "lo/L.mdx": `<S id="l">
Low one.
</S>

<S id="l2">
Low two.
</S>
`,
};

const T7_5_2 = defineProductTest({
  id: "T7.5-2",
  title:
    "forbidden rules: an edge whose source matches `from` and target " +
    "matches `to` is a check finding carrying the rule name and the " +
    "offending edge (exit 1); non-matching edges are not; `kinds` restricts " +
    "which edges are evaluated (SPEC 7.5, 14.12)",
  run: async (product) => {
    await expectPolicyFindings(
      product,
      FORBIDDEN_FILES,
      [
        {
          rule: "no-hi-to-lo",
          edge: { from: "hi/H.mdx#bad", to: "lo/L.mdx#l", kind: "depends" },
        },
      ],
      "T7.5-2 (matching semantics)",
    );

    await expectPolicyFindings(
      product,
      FORBIDDEN_KINDS_FILES,
      [
        {
          rule: "no-embed",
          edge: { from: "hi/H.mdx#has", to: "lo/L.mdx#l2", kind: "embeds" },
        },
      ],
      "T7.5-2 (kinds restriction — the depends edge matches from and to but " +
        "its kind is not evaluated)",
    );
  },
});

// ---------------------------------------------------------------------------
// T7.5-3 — allowedOnly
// ---------------------------------------------------------------------------

// Every edge from a `from`-matching source must have a `to`-matching target;
// each violating edge is a separate finding — staged as TWO violating edges
// from ONE source node (a per-source-deduplicating product loses one):
//
//   app/A.mdx#fine  --depends--> good/G.mdx#g    allowed → no finding
//   app/A.mdx#bad   --depends--> other/O.mdx#o1  violation
//   app/A.mdx#bad   --depends--> other/O.mdx#o2  violation (separate)
//   other/O.mdx#o3  --depends--> other/O.mdx#o1  source unmatched → none
const ALLOWED_ONLY_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    app: ["app/**/*.mdx"],
    good: ["good/**/*.mdx"],
    other: ["other/**/*.mdx"]
  },
  policy: [
    {
      name: "app-targets-good",
      type: "allowedOnly",
      from: { group: "app" },
      to: { group: "good" }
    }
  ]
})
`,
  "app/A.mdx": `import G from "../good/G.xspec"
import O from "../other/O.xspec"

<S id="fine" d={G.g}>
Depends on the allowed group.
</S>

<S id="bad" d={[O.o1, O.o2]}>
Depends twice outside the allowed group.
</S>
`,
  "good/G.mdx": mdxSection("g"),
  "other/O.mdx": `<S id="o1">
Other one.
</S>

<S id="o2">
Other two.
</S>

<S id="o3" d={"o1"}>
Unconstrained: this source is not in the app group, and its target is not
in the allowed group either.
</S>
`,
};

const T7_5_3 = defineProductTest({
  id: "T7.5-3",
  title:
    "allowedOnly rules: every edge from a `from`-matching source must have " +
    "a `to`-matching target; each violating edge is a separate finding, and " +
    "edges from non-matching sources are unconstrained (SPEC 7.5, 14.12)",
  run: async (product) => {
    await expectPolicyFindings(
      product,
      ALLOWED_ONLY_FILES,
      [
        {
          rule: "app-targets-good",
          edge: {
            from: "app/A.mdx#bad",
            to: "other/O.mdx#o1",
            kind: "depends",
          },
        },
        {
          rule: "app-targets-good",
          edge: {
            from: "app/A.mdx#bad",
            to: "other/O.mdx#o2",
            kind: "depends",
          },
        },
      ],
      "T7.5-3",
    );
  },
});

// ---------------------------------------------------------------------------
// T7.5-4 — selectors
// ---------------------------------------------------------------------------

// (a) `group` selectors — nodes of spec groups and code locations of code
// groups, with `kind` where needed: `dual` names both a spec and a code
// group; one edge is sourced at the spec side's node, one at the code side's
// location. The kind-qualified rules must each flag exactly their side (a
// kind-ignoring product flags both edges under both rules).
const SELECTOR_KIND_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    dual: ["dspec/**/*.mdx"],
    tgt: ["tgt/**/*.mdx"]
  },
  code: {
    dual: ["dcode/**/*.ts"]
  },
  policy: [
    {
      name: "spec-side",
      type: "forbidden",
      from: { group: "dual", kind: "spec" },
      to: { group: "tgt" }
    },
    {
      name: "code-side",
      type: "forbidden",
      from: { group: "dual", kind: "code" },
      to: { group: "tgt" }
    }
  ]
})
`,
  "dspec/S.mdx": `import T from "../tgt/T.xspec"

<S id="s" d={T.t}>
Spec-side dependence on the target.
</S>
`,
  "dcode/c.ts": `import T from "../tgt/T.xspec"

T.t
`,
  "tgt/T.mdx": mdxSection("t"),
};

// (b) `files` selectors match by glob, on both sides: only the edge whose
// source file matches `from`'s glob AND whose target file matches `to`'s
// glob is flagged.
const SELECTOR_FILES_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    all: ["specs/**/*.mdx"]
  },
  policy: [
    {
      name: "inner-to-c",
      type: "forbidden",
      from: { files: "specs/inner/*.mdx" },
      to: { files: "specs/C.mdx" }
    }
  ]
})
`,
  "specs/inner/A.mdx": `import C from "../C.xspec"
import D from "../D.xspec"

<S id="a" d={C.c}>
Inner depends on C.
</S>

<S id="a2" d={D.d}>
Inner depends on D — the to glob does not match this target.
</S>
`,
  "specs/B.mdx": `import C from "./C.xspec"

<S id="b" d={C.c}>
Outer depends on C — the from glob does not match this source.
</S>
`,
  "specs/C.mdx": mdxSection("c"),
  "specs/D.mdx": mdxSection("d"),
};

// (c) `tags` selectors match nodes carrying AT LEAST ONE listed tag: `r`
// carries red only, `b` carries blue (plus the unlisted green) — both match
// ["red", "blue"] (an all-tags product matches neither); untagged `u` does
// not.
const SELECTOR_TAGS_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    pol: ["pol/**/*.mdx"],
    tgt: ["tgt/**/*.mdx"]
  },
  policy: [
    {
      name: "no-tagged",
      type: "forbidden",
      from: { tags: ["red", "blue"] },
      to: { group: "tgt" }
    }
  ]
})
`,
  "pol/P.mdx": `import T from "../tgt/T.xspec"

<S id="r" tags="red" d={T.t}>
Red-tagged dependence.
</S>

<S id="b" tags="blue green" d={T.t}>
Blue-and-green-tagged dependence.
</S>

<S id="u" d={T.t}>
Untagged dependence.
</S>
`,
  "tgt/T.mdx": mdxSection("t"),
};

const T7_5_4 = defineProductTest({
  id: "T7.5-4",
  title:
    "selectors: `group` (with `kind` where needed) matches nodes of spec " +
    "groups and code locations of code groups; `files` matches by glob on " +
    "both sides; `tags` matches nodes carrying at least one listed tag " +
    "(SPEC 7.5, 14.12)",
  run: async (product) => {
    await expectPolicyFindings(
      product,
      SELECTOR_KIND_FILES,
      [
        {
          rule: "spec-side",
          edge: { from: "dspec/S.mdx#s", to: "tgt/T.mdx#t", kind: "depends" },
        },
        {
          rule: "code-side",
          edge: { from: "dcode/c.ts", to: "tgt/T.mdx#t", kind: "references" },
        },
      ],
      "T7.5-4 (group selectors with kind over the ambiguous name dual — the " +
        "spec-side rule flags only the spec node's edge, the code-side rule " +
        "only the code location's edge)",
    );

    await expectPolicyFindings(
      product,
      SELECTOR_FILES_FILES,
      [
        {
          rule: "inner-to-c",
          edge: {
            from: "specs/inner/A.mdx#a",
            to: "specs/C.mdx#c",
            kind: "depends",
          },
        },
      ],
      "T7.5-4 (files selectors — glob-unmatched source and glob-unmatched " +
        "target both stay unflagged)",
    );

    await expectPolicyFindings(
      product,
      SELECTOR_TAGS_FILES,
      [
        {
          rule: "no-tagged",
          edge: { from: "pol/P.mdx#b", to: "tgt/T.mdx#t", kind: "depends" },
        },
        {
          rule: "no-tagged",
          edge: { from: "pol/P.mdx#r", to: "tgt/T.mdx#t", kind: "depends" },
        },
      ],
      "T7.5-4 (tags selector — at-least-one-listed-tag matching)",
    );
  },
});

// ---------------------------------------------------------------------------
// T7.5-5 — captures
// ---------------------------------------------------------------------------

// (a) `$1-$2.ts` against `a-b-c.ts` captures ($1 = a, $2 = b-c): observed
// through to-expansion agreement (module header). The source file references
// nodes in specs/a/b-c.mdx (the shortest-match expansion of
// `specs/$1/$2.mdx`) and specs/a-b/c.mdx (the greedy parse's expansion,
// $1 = a-b / $2 = c); exactly the first edge is a finding.
const CAPTURE_PAIR_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    specs: ["specs/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  },
  policy: [
    {
      name: "pair",
      type: "forbidden",
      from: { files: "src/$1-$2.ts" },
      to: { files: "specs/$1/$2.mdx" }
    }
  ]
})
`,
  "src/a-b-c.ts": `import GOOD from "../specs/a/b-c.xspec"
import ALT from "../specs/a-b/c.xspec"

GOOD.m
ALT.n
`,
  "specs/a/b-c.mdx": mdxSection("m"),
  "specs/a-b/c.mdx": mdxSection("n"),
};

// (b) `*$1*` against `abc` captures $1 = a (the leading `*` takes the empty
// string, the capture takes its one-byte minimum). Targets exist for the
// correct expansion (tgt/a.mdx), the greedy-capture expansion (tgt/abc.mdx),
// and the greedy-leading-`*` expansion (tgt/c.mdx); exactly the first is
// flagged.
const CAPTURE_STAR_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    grp: ["grp/**/*.mdx"],
    tgt: ["tgt/**/*.mdx"]
  },
  policy: [
    {
      name: "star",
      type: "forbidden",
      from: { files: "grp/*$1*/F.mdx" },
      to: { files: "tgt/$1.mdx" }
    }
  ]
})
`,
  "grp/abc/F.mdx": `import A from "../../tgt/a.xspec"
import X from "../../tgt/abc.xspec"
import C from "../../tgt/c.xspec"

<S id="f" d={[A.a, X.x, C.c]}>
Depends on every candidate expansion's node.
</S>
`,
  "tgt/a.mdx": mdxSection("a"),
  "tgt/abc.mdx": mdxSection("x"),
  "tgt/c.mdx": mdxSection("c"),
};

// (c) A capture never matches the empty string or `/`: `pre/$1x.mdx` matches
// pre/ax.mdx ($1 = a) but neither pre/x.mdx ($1 would be empty) nor
// pre/d/ex.mdx ($1 would be d/e — a whole-path-regex product matches it).
const CAPTURE_LIMITS_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    pre: ["pre/**/*.mdx"],
    tgt: ["tgt/**/*.mdx"]
  },
  policy: [
    {
      name: "cap",
      type: "forbidden",
      from: { files: "pre/$1x.mdx" },
      to: { group: "tgt" }
    }
  ]
})
`,
  "pre/ax.mdx": `import T from "../tgt/T.xspec"

<S id="s1" d={T.t}>
Source whose file matches with a one-byte capture.
</S>
`,
  "pre/x.mdx": `import T from "../tgt/T.xspec"

<S id="s2" d={T.t}>
Source whose file would need an empty capture.
</S>
`,
  "pre/d/ex.mdx": `import T from "../../tgt/T.xspec"

<S id="s3" d={T.t}>
Source whose file would need a capture spanning a slash.
</S>
`,
  "tgt/T.mdx": mdxSection("t"),
};

// (d) The mirror-structure allowedOnly fixture: every edge from src/$1.ts
// must target a node of m/$1.mdx — src/good.ts → m/good.mdx#g agrees (no
// finding), src/evil.ts → m/wrong.mdx#w disagrees (a finding).
const CAPTURE_MIRROR_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    m: ["m/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  },
  policy: [
    {
      name: "mirror",
      type: "allowedOnly",
      from: { files: "src/$1.ts" },
      to: { files: "m/$1.mdx" }
    }
  ]
})
`,
  "src/good.ts": `import G from "../m/good.xspec"

G.g
`,
  "src/evil.ts": `import W from "../m/wrong.xspec"

W.w
`,
  "m/good.mdx": mdxSection("g"),
  "m/wrong.mdx": mdxSection("w"),
};

const CAPTURE_PAIR_EXPECTED: readonly PolicyExpectation[] = [
  {
    rule: "pair",
    edge: {
      from: "src/a-b-c.ts",
      to: "specs/a/b-c.mdx#m",
      kind: "references",
    },
  },
];

const T7_5_5 = defineProductTest({
  id: "T7.5-5",
  title:
    "captures: $1-$2.ts against a-b-c.ts captures a and b-c, *$1* against " +
    "abc captures a (shortest-match left to right), a capture never matches " +
    "/ or the empty string, a to with captures matches only agreeing " +
    "expansions (mirror-structure allowedOnly fixture), and the " +
    "disambiguation is deterministic across repeat runs (SPEC 7.5, 14.12, " +
    "12.0, H-6)",
  run: async (product) => {
    // (a) The $1-$2 tuple, plus determinism: the identical `check --json`
    // twice with byte-identical outputs (H-6) — the capture-dependent
    // finding set cannot flap between parses.
    await withWorkspace({ files: CAPTURE_PAIR_FILES }, async (workspace) => {
      const base = "T7.5-5 ($1-$2 shortest-match tuple)";
      await buildOk(
        product,
        workspace,
        `${base} \`build\` — sources are valid and build does not evaluate ` +
          `policy (SPEC 12.1, 7.5)`,
      );
      const label = `${base} \`check --json\``;
      const { first } = await assertRunTwiceDeterministic({
        binding: product,
        run: { cwd: workspace.root, argv: ["check", "--json"] },
        context:
          `${label} run twice — left-to-right shortest-match ` +
          `disambiguation is deterministic (SPEC 7.5, 12.0, H-6)`,
      });
      const result = first;
      if (result.signal !== null || result.exitCode !== 1) {
        fail(
          `${label}: policy violations are findings and cause exit 1 ` +
            `(SPEC 7.5, 12.0); got ${summarizeResult(result)}`,
        );
      }
      assertPolicyFindings(
        decodeFindingsReport(parseJsonStdout(result, label), label).findings,
        CAPTURE_PAIR_EXPECTED,
        `${label} — $1 takes as few bytes as possible while the remainder ` +
          `still matches, so a-b-c.ts captures ($1 = a, $2 = b-c) and only ` +
          `the specs/a/b-c.mdx expansion agrees (a greedy parse flags ` +
          `specs/a-b/c.mdx instead)`,
      );
    });

    // (b) *$1* against abc captures a.
    await expectPolicyFindings(
      product,
      CAPTURE_STAR_FILES,
      [
        {
          rule: "star",
          edge: { from: "grp/abc/F.mdx#f", to: "tgt/a.mdx#a", kind: "depends" },
        },
      ],
      "T7.5-5 (*$1* against abc — the leading * takes the empty string and " +
        "$1 its one-byte minimum, so only the tgt/a.mdx expansion agrees; " +
        "greedy-capture and greedy-leading-* parses flag tgt/abc.mdx or " +
        "tgt/c.mdx instead)",
    );

    // (c) A capture never matches the empty string or a slash.
    await expectPolicyFindings(
      product,
      CAPTURE_LIMITS_FILES,
      [
        {
          rule: "cap",
          edge: { from: "pre/ax.mdx#s1", to: "tgt/T.mdx#t", kind: "depends" },
        },
      ],
      "T7.5-5 (capture limits — pre/$1x.mdx matches neither pre/x.mdx, " +
        "whose capture would be empty, nor pre/d/ex.mdx, whose capture " +
        "would span a slash)",
    );

    // (d) The mirror-structure allowedOnly fixture: agreeing pairs pass,
    // disagreeing ones violate.
    await expectPolicyFindings(
      product,
      CAPTURE_MIRROR_FILES,
      [
        {
          rule: "mirror",
          edge: {
            from: "src/evil.ts",
            to: "m/wrong.mdx#w",
            kind: "references",
          },
        },
      ],
      "T7.5-5 (mirror-structure allowedOnly — src/good.ts's edge into " +
        "m/good.mdx agrees with its expansion and passes; src/evil.ts's " +
        "edge into m/wrong.mdx disagrees and violates)",
    );
  },
});

// ---------------------------------------------------------------------------
// T7.5-6 — build vs check
// ---------------------------------------------------------------------------

// A workspace full of policy violations: every hi node's dependence violates
// the rule (two violations, nothing else wrong).
const BUILD_VS_CHECK_FILES: Readonly<Record<string, string>> = {
  "xspec.config.ts": `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    hi: ["hi/**/*.mdx"],
    lo: ["lo/**/*.mdx"]
  },
  policy: [
    {
      name: "no-hi-to-lo",
      type: "forbidden",
      from: { group: "hi" },
      to: { group: "lo" }
    }
  ]
})
`,
  "hi/H.mdx": `import L from "../lo/L.xspec"

<S id="h1" d={L.l1}>
First violating dependence.
</S>

<S id="h2" d={L.l2}>
Second violating dependence.
</S>
`,
  "lo/L.mdx": `<S id="l1">
Low one.
</S>

<S id="l2">
Low two.
</S>
`,
};

const BUILD_VS_CHECK_EXPECTED: readonly PolicyExpectation[] = [
  {
    rule: "no-hi-to-lo",
    edge: { from: "hi/H.mdx#h1", to: "lo/L.mdx#l1", kind: "depends" },
  },
  {
    rule: "no-hi-to-lo",
    edge: { from: "hi/H.mdx#h2", to: "lo/L.mdx#l2", kind: "depends" },
  },
];

const T7_5_6 = defineProductTest({
  id: "T7.5-6",
  title:
    "build vs check: build succeeds (exit 0) and regenerates output on a " +
    "workspace full of policy violations — a tampered generated module is " +
    "byte-restored by rebuilding — while only check reports the violations, " +
    "exit 1 (SPEC 7.5, 12.1, 14.12)",
  run: async (product) => {
    await withWorkspace({ files: BUILD_VS_CHECK_FILES }, async (workspace) => {
      // build succeeds despite the violations (12.1; a product reporting
      // policy findings would exit 1 — 7.5 — and fail here).
      await buildOk(
        product,
        workspace,
        "T7.5-6 first `build` — build does not evaluate policy: it succeeds " +
          "on a workspace full of policy violations (SPEC 12.1, 7.5, 14.12)",
      );

      // …and regenerates output: tamper with a generated module, rebuild,
      // and the module is byte-restored (12.1 regenerates every derived
      // file; 12.0 makes the regenerated bytes deterministic, so the
      // product-to-itself byte comparison is exact — H-4).
      const moduleRel = "hi/H.xspec.ts";
      const original = await readGeneratedModule(
        workspace,
        moduleRel,
        "T7.5-6 after the first build (SPEC 13.1: hi/H.mdx generates " +
          "hi/H.xspec.ts in the source file's directory)",
      );
      await workspace.file(moduleRel, `${original}// tampered\n`);
      await buildOk(
        product,
        workspace,
        "T7.5-6 second `build` over the tampered module — still exit 0 " +
          "despite the policy violations (SPEC 12.1)",
      );
      await assertFileBytes(
        workspace.path(moduleRel),
        original,
        "T7.5-6: the rebuild regenerated the tampered module byte-for-byte " +
          "— build regenerates output whether or not policy is satisfied " +
          "(SPEC 12.1, 12.0, H-4)",
      );

      // Only check reports the violations: exit 1 with exactly the two
      // findings, each carrying the rule name and its offending edge.
      const label = "T7.5-6 `check --json`";
      assertPolicyFindings(
        await checkFindings(product, workspace, label),
        BUILD_VS_CHECK_EXPECTED,
        `${label} — policy violations are reported by check and only check ` +
          `(SPEC 7.5, 14.12)`,
      );
    });
  },
});

/** TEST-SPEC §7.4–7.5 T7.4-1…T7.5-6, in canonical ID order (SUITE-29). */
export const section74to75Tests: readonly ProductTestEntry[] = [
  T7_4_1,
  T7_4_2,
  T7_5_1,
  T7_5_2,
  T7_5_3,
  T7_5_4,
  T7_5_5,
  T7_5_6,
];
