// TEST-SPEC §4 preamble (generated TypeScript modules) — SUITE-12:
// T4-1 … T4-4.
//
// Registered product-facing bodies (C-2 "one code path"): each builds its own
// fresh workspace (H-1), drives the product strictly as a subprocess (H-2),
// asserts exact exit codes (H-5), decodes output through the H-3 adapters,
// and rejects a product only via diagnosed assertion failures (H-8).
// Consumer-side contracts — aliased bindings type-checking, `text` at
// runtime, and the type-only value-use TypeScript errors — run under standard
// TypeScript tooling with no xspec runtime dependency (SPEC 13.1) through
// helpers/tooling.ts; consumer files compile and run in CommonJS mode under
// the driver's NodeNext defaults, where the spec-fixed `./NAME.xspec`
// specifier resolves by Node's extension lookup.
//
// SPEC 4: each `NAME.mdx` generates `NAME.xspec.ts` beside it (13.1),
// beginning with a header identifying it as generated by xspec from its
// source file. In a TypeScript file, an import declaration is a spec module
// import exactly when its specifier ends in `.xspec`; the 2.1 specifier form
// and resolution apply and the target must be a discovered spec source
// (14.15); the permitted bindings are the default and `text` exports, each
// optionally aliased, possibly type-only; every other module-linking form
// whose specifier ends in `.xspec` — a dynamic `import()` with a static
// specifier, export declarations in all forms, `import X = require(…)` — is
// invalid (14.15), as is any of the four module-linking forms whose relative
// specifier designates a derived-file path (13.4) other than through
// `.xspec`; a dynamic `import()` with a non-static specifier is not analyzed
// and records nothing; imports colliding on a binding identifier are 14.15
// when either import is a spec module import.
//
// Conservative operationalizations (noted per H-4 — wording is free, so only
// the stated observables are asserted):
// - T4-1 "header": the module's leading comment region — line/block comments
//   (and whitespace) before the first non-comment code. "Mentions the source
//   path" is asserted as containing the source file's name (`NAME.mdx`): the
//   module sits beside its source (13.1), so the name identifies the file and
//   every path rendering — basename, relative, workspace-relative, absolute —
//   contains it.
// - Location assertions: every offending statement in T4-2 is staged at a
//   known byte offset in a pure-ASCII `src/app.ts`, so string indices are
//   byte offsets and each 14.15 finding must fall within the offending
//   statement's own byte window (end-widened by one byte for line-granular
//   locations, support.ts byteWindow).

import type { GraphEdge } from "../../helpers/adapters/index.js";
import { decodeEdgesReport } from "../../helpers/adapters/index.js";
import {
  assertBytesEqual,
  assertExitCode,
  fail,
} from "../../helpers/assertions.js";
import { defineProductTest } from "../../helpers/registry.js";
import type { ProductTestEntry } from "../../helpers/registry.js";
import type { ProductBinding } from "../../helpers/subprocess.js";
import {
  assertCompileErrorAt,
  assertNoCompileErrors,
  ConsumerProject,
  formatConsumerDiagnostic,
  runConsumer,
} from "../../helpers/tooling.js";
import { TestWorkspace } from "../../helpers/workspace.js";
import {
  assertConditionCounts,
  assertEdgeSetEqual,
  assertFindingLocated,
  buildFindings,
  buildOk,
  byteWindow,
  expectExit,
  readGeneratedModule,
  runJson,
} from "./support.js";

// Minimal declarative configuration (SPEC 7): exactly one spec group.
const SPECS_ONLY_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  }
})
`;

// One spec group plus one code group (SPEC 7.2): TypeScript files under
// `src/` are discovered code sources, so `build` analyzes their imports and
// spec-module usage (4, 4.5).
const SPEC_AND_CODE_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  }
})
`;

// The same plus enabled Markdown emission, for the T4-2 arms whose derived
// path is a configured Markdown emit destination — those exist exactly while
// emission is enabled (SPEC 7.3), with the default next-to-source placement.
const MARKDOWN_EMIT_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  },
  markdown: { emit: true }
})
`;

/** Stage a fresh workspace (config plus `files`), run `body`, dispose (H-1). */
async function withWorkspace<T>(
  config: string,
  files: Readonly<Record<string, string>>,
  body: (workspace: TestWorkspace) => Promise<T>,
): Promise<T> {
  const workspace = await TestWorkspace.create({
    files: { "xspec.config.ts": config, ...files },
  });
  try {
    return await body(workspace);
  } finally {
    await workspace.dispose();
  }
}

/** `query edges --from <graph-node>`, decoded (SPEC 11). */
async function queryEdgesFrom(
  product: ProductBinding,
  workspace: TestWorkspace,
  from: string,
  context: string,
): Promise<readonly GraphEdge[]> {
  const label = `${context} \`query edges --from ${from}\``;
  return decodeEdgesReport(
    await runJson(
      product,
      workspace,
      ["query", "edges", "--from", from],
      label,
    ),
    label,
  );
}

// ---------------------------------------------------------------------------
// T4-1
// ---------------------------------------------------------------------------

// Two spec sources with distinct names, one in a subdirectory, so each
// generated module's header must identify its *own* source file — a constant
// header copied between modules fails the per-module name assertion.
const T4_1_FILES = {
  "specs/A.mdx": '<S id="alpha">\nAlpha behavior.\n</S>\n',
  "specs/sub/B.mdx": '<S id="beta">\nBeta behavior.\n</S>\n',
} as const;

/**
 * The module's leading comment region: line and block comments, with
 * interleaving whitespace, from the start of the file up to the first
 * non-comment code. An unterminated block comment does not extend the
 * region (it is not a well-formed header).
 */
function leadingCommentRegion(moduleText: string): string {
  let at = 0;
  let end = 0;
  while (at < moduleText.length) {
    if (/\s/.test(moduleText[at]!)) {
      at += 1;
      continue;
    }
    if (moduleText.startsWith("//", at)) {
      const lineEnd = moduleText.indexOf("\n", at);
      at = lineEnd === -1 ? moduleText.length : lineEnd + 1;
      end = at;
      continue;
    }
    if (moduleText.startsWith("/*", at)) {
      const close = moduleText.indexOf("*/", at + 2);
      if (close === -1) break;
      at = close + 2;
      end = at;
      continue;
    }
    break;
  }
  return moduleText.slice(0, end);
}

const T4_1 = defineProductTest({
  id: "T4-1",
  title:
    "each generated module begins with a header identifying it as generated by xspec from its source file — header present, mentions xspec and the source file, wording free (SPEC 4, 13.1)",
  run: async (product) => {
    await withWorkspace(SPECS_ONLY_CONFIG, T4_1_FILES, async (workspace) => {
      await buildOk(product, workspace, "T4-1 `build` over two spec sources");
      for (const [modulePath, sourceName] of [
        ["specs/A.xspec.ts", "A.mdx"],
        ["specs/sub/B.xspec.ts", "B.mdx"],
      ] as const) {
        const context = `T4-1 generated module ${modulePath}`;
        const moduleText = await readGeneratedModule(
          workspace,
          modulePath,
          context,
        );
        const header = leadingCommentRegion(moduleText);
        if (header === "") {
          fail(
            `${context}: the module must begin with a header — a comment region ` +
              `before any code (SPEC 4: "MUST begin with a header"); the module ` +
              `starts with ${JSON.stringify(moduleText.slice(0, 120))}`,
          );
        }
        if (!/xspec/i.test(header)) {
          fail(
            `${context}: the header must identify the module as generated by ` +
              `xspec (SPEC 4) — "xspec" does not appear in the leading comment ` +
              `region: ${JSON.stringify(header)}`,
          );
        }
        if (!header.includes(sourceName)) {
          fail(
            `${context}: the header must identify the module's source file ` +
              `(SPEC 4: "from its source file") — expected the leading comment ` +
              `region to mention ${JSON.stringify(sourceName)} (every rendering ` +
              `of the source path contains the file name); got ` +
              JSON.stringify(header),
          );
        }
      }
    });
  },
});

// ---------------------------------------------------------------------------
// T4-2
// ---------------------------------------------------------------------------

// Every arm's workspace: the configuration, a valid discovered spec source
// `specs/BASE.mdx` (so arms whose specifier names it carry the specifier or
// binding form as their only defect), any arm-specific extra files, and
// `src/app.ts` holding exactly the arm's statements — the offending
// construct(s) start at byte 0, everything pure ASCII.
const T4_2_BASE_FILES = {
  "specs/BASE.mdx": '<S id="core">\nCore behavior.\n</S>\n',
} as const;

/** One invalid TS import-rule arm: a workspace differing only in src/app.ts. */
interface InvalidTsImportArm {
  /** Which SPEC 4 invalid case this is (failure diagnostics). */
  readonly name: string;
  /** The statements of `src/app.ts`, staged one per line from byte 0. */
  readonly statements: readonly string[];
  /**
   * Upper bound on accepted 14.15 findings. Duplicate-binding arms accept 2:
   * SPEC 2.1/14.15 define one condition over the colliding pair, and whether
   * a product reports the collision once or per import is not fixed.
   */
  readonly maxFindings?: number;
  /** Configuration override (defaults to SPEC_AND_CODE_CONFIG). */
  readonly config?: string;
  /** Files staged beside the base files. */
  readonly extraFiles?: Readonly<Record<string, string>>;
}

// The `.xspec`-specifier rules (SPEC 4: target must be a discovered spec
// source; the 2.1 specifier form applies in TS; only the default and `text`
// exports may be bound; no other module-linking form may carry a `.xspec`
// specifier).
const XSPEC_RULE_ARMS: readonly InvalidTsImportArm[] = [
  {
    name: "a `.xspec` specifier designating an existing file that is not a discovered spec source",
    statements: ['import MOD from "../docs/EXTRA.xspec";'],
    extraFiles: {
      "docs/EXTRA.mdx": '<S id="extra">\nOutside every spec group.\n</S>\n',
    },
  },
  {
    name: "a `.xspec` specifier designating a nonexistent file",
    statements: ['import MOD from "../specs/missing.xspec";'],
  },
  {
    name: "a bare specifier ending `.xspec`",
    statements: ['import MOD from "BASE.xspec";'],
  },
  {
    name: "an absolute specifier ending `.xspec`",
    statements: ['import MOD from "/specs/BASE.xspec";'],
  },
  {
    name: "a named binding other than `text`",
    statements: ['import { core } from "../specs/BASE.xspec";'],
  },
  {
    name: "a namespace binding",
    statements: ['import * as NS from "../specs/BASE.xspec";'],
  },
  {
    name: "a dynamic `import()` with a static `.xspec` specifier",
    statements: ['void import("../specs/BASE.xspec");'],
  },
  {
    name: "an `export * from` declaration with a `.xspec` specifier",
    statements: ['export * from "../specs/BASE.xspec";'],
  },
  {
    name: "an `export * as NS from` declaration with a `.xspec` specifier",
    statements: ['export * as NS from "../specs/BASE.xspec";'],
  },
  {
    // Even the permitted-binding name is not re-exportable: no re-export
    // carries a spec module's nodes or `text` past 4.5.
    name: "an `export { … } from` declaration with a `.xspec` specifier",
    statements: ['export { text } from "../specs/BASE.xspec";'],
  },
  {
    name: "a type-only `export type { … } from` declaration with a `.xspec` specifier",
    statements: ['export type { text } from "../specs/BASE.xspec";'],
  },
  {
    name: "an `import X = require(…)` declaration with a `.xspec` specifier",
    statements: ['import MOD = require("../specs/BASE.xspec");'],
  },
];

// Derived-path arms (SPEC 4, 13.4): the full cross product of the four
// module-linking forms SPEC 4 names and the three derived-file path kinds of
// 13.4 — a file name containing `.xspec.` (the generated module's own path,
// consumed only through its `.xspec` specifier), a path under `.xspec/`, and
// a configured Markdown emit destination (a derived path exactly while
// emission is enabled, whether or not emission has yet run, SPEC 7.3 — so
// those arms run under MARKDOWN_EMIT_CONFIG). The classification is by path
// (13.4), so no file needs to exist at the specifier's target.
const MODULE_LINKING_FORMS: readonly {
  readonly form: string;
  readonly statement: (specifier: string) => string;
}[] = [
  {
    form: "an import declaration",
    statement: (specifier) => `import MOD from "${specifier}";`,
  },
  {
    form: "an export declaration",
    statement: (specifier) => `export * from "${specifier}";`,
  },
  {
    form: "an `import X = require(…)` declaration",
    statement: (specifier) => `import MOD = require("${specifier}");`,
  },
  {
    form: "a static-specifier dynamic `import()`",
    statement: (specifier) => `void import("${specifier}");`,
  },
];

const DERIVED_PATH_KINDS: readonly {
  readonly kind: string;
  readonly specifier: string;
  readonly config?: string;
}[] = [
  {
    kind: "a file name containing `.xspec.` (`../specs/BASE.xspec.ts` directly)",
    specifier: "../specs/BASE.xspec.ts",
  },
  {
    kind: "a path under `.xspec/`",
    specifier: "../.xspec/data.ts",
  },
  {
    kind: "a configured Markdown emit destination (emission enabled)",
    specifier: "../specs/BASE.md",
    config: MARKDOWN_EMIT_CONFIG,
  },
];

const DERIVED_PATH_ARMS: readonly InvalidTsImportArm[] =
  MODULE_LINKING_FORMS.flatMap((form) =>
    DERIVED_PATH_KINDS.map((path) => ({
      name: `${form.form} whose relative specifier designates ${path.kind}`,
      statements: [form.statement(path.specifier)],
      config: path.config,
    })),
  );

// Duplicate-binding arms (SPEC 4, 2.1, 14.15 — "in either kind of file"; the
// MDX side is T2.1-3's): a collision fails when either import is a spec
// module import — spec with spec, and spec with non-spec in both orders.
const DUPLICATE_BINDING_ARMS: readonly InvalidTsImportArm[] = [
  {
    name: "two spec module imports binding one identifier",
    statements: [
      'import MOD from "../specs/BASE.xspec";',
      'import MOD from "../specs/OTHER.xspec";',
    ],
    extraFiles: {
      "specs/OTHER.mdx": '<S id="other">\nOther behavior.\n</S>\n',
    },
    maxFindings: 2,
  },
  {
    name: "a spec module import colliding with a later non-spec import",
    statements: [
      'import MOD from "../specs/BASE.xspec";',
      'import MOD from "node:path";',
    ],
    maxFindings: 2,
  },
  {
    name: "a non-spec import colliding with a later spec module import",
    statements: [
      'import MOD from "node:path";',
      'import MOD from "../specs/BASE.xspec";',
    ],
    maxFindings: 2,
  },
];

/**
 * Run one invalid-import arm: `build --json` exits 1 with only 14.15
 * findings — exactly one for a single-statement arm, one or two for a
 * colliding pair — each locating the importing code file and falling within
 * an offending statement's own byte window (SPEC 14: errors identify file
 * and location).
 */
async function runInvalidTsImportArm(
  product: ProductBinding,
  arm: InvalidTsImportArm,
  testId: string,
): Promise<void> {
  const context = `${testId} \`build --json\` over ${arm.name}`;
  const windows: { start: number; end: number }[] = [];
  let prefix = "";
  for (const statement of arm.statements) {
    windows.push(byteWindow(prefix, statement));
    prefix += statement + "\n";
  }
  await withWorkspace(
    arm.config ?? SPEC_AND_CODE_CONFIG,
    {
      ...T4_2_BASE_FILES,
      ...arm.extraFiles,
      "src/app.ts": prefix,
    },
    async (workspace) => {
      const findings = await buildFindings(product, workspace, context);
      const max = arm.maxFindings ?? 1;
      if (max === 1) {
        assertConditionCounts(findings, { "14.15": 1 }, context);
        assertFindingLocated(
          findings[0]!,
          { file: "src/app.ts", window: windows[0]! },
          `${context}: the 14.15 finding`,
        );
        return;
      }
      const conditions = findings.map((finding) => finding.condition);
      if (
        findings.length < 1 ||
        findings.length > max ||
        conditions.some((condition) => condition !== "14.15")
      ) {
        fail(
          `${context}: expected the colliding pair to report condition 14.15 — ` +
            `one finding for the collision, or one per import — got ` +
            JSON.stringify(conditions),
        );
      }
      for (const finding of findings) {
        const findingContext = `${context}: a 14.15 finding`;
        assertFindingLocated(finding, { file: "src/app.ts" }, findingContext);
        for (const { range } of finding.locations) {
          const within = windows.some(
            (window) => range.start >= window.start && range.end <= window.end,
          );
          if (!within) {
            fail(
              `${findingContext}: every location [${String(range.start)}, ` +
                `${String(range.end)}) must point at one of the colliding ` +
                `import statements (byte windows ${JSON.stringify(windows)})`,
            );
          }
        }
      }
    },
  );
}

// Positive arm: a dynamic `import()` with a non-static specifier is not
// analyzed. The identifier holds a string that *would* designate the
// discovered spec source — a product that analyzed the call (e.g. by constant
// propagation) would have to report the always-invalid static-specifier
// dynamic import (14.15) and fail the exit-0 expectation; a conforming
// product records nothing from the file.
const NON_STATIC_DYNAMIC_SOURCE = [
  'const target = "../specs/BASE.xspec";',
  "void import(target);",
  "",
].join("\n");

// Positive arm: two colliding non-spec imports — neither is a spec module
// import, so the collision is no xspec finding, and the unused colliding
// bindings trigger no xspec error (TypeScript's own complaint is outside
// xspec's validations).
const NON_SPEC_COLLISION_SOURCE = [
  'import MOD from "node:path";',
  'import MOD from "node:url";',
  "",
].join("\n");

const T4_2 = defineProductTest({
  id: "T4-2",
  title:
    "TS import rules: undiscovered/nonexistent/bare/absolute `.xspec` specifiers, bindings other than the default and `text`, static-specifier dynamic `import()`, every export-declaration form, `import X = require(…)`, and derived-path specifiers through each module-linking form all fail with 14.15; a non-static dynamic `import()` is not analyzed; binding collisions are 14.15 when either import is a spec module import, and no finding otherwise (SPEC 4, 2.1, 13.4, 14.15)",
  // Many small workspaces (27 negative arms plus two positive ones), each
  // one product invocation: a wider hang budget than the default (H-8 hang
  // guard only, never an assertion — H-10).
  timeoutMs: 240_000,
  run: async (product) => {
    for (const arm of [
      ...XSPEC_RULE_ARMS,
      ...DERIVED_PATH_ARMS,
      ...DUPLICATE_BINDING_ARMS,
    ]) {
      await runInvalidTsImportArm(product, arm, "T4-2");
    }

    // Non-static dynamic import: build succeeds, no edges recorded.
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      { ...T4_2_BASE_FILES, "src/app.ts": NON_STATIC_DYNAMIC_SOURCE },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-2 `build` with a dynamic `import()` whose specifier is a " +
            "non-static expression (an identifier)",
        );
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/app.ts", "T4-2"),
          [],
          "T4-2 a non-static dynamic `import()` is not analyzed: no edge " +
            "leaves the code file (SPEC 4)",
        );
      },
    );

    // Two colliding non-spec imports: not an xspec finding.
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      { ...T4_2_BASE_FILES, "src/app.ts": NON_SPEC_COLLISION_SOURCE },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-2 `build` with two colliding non-spec imports (no spec module " +
            "import participates, so no xspec finding — SPEC 4, 14.15)",
        );
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T4-3
// ---------------------------------------------------------------------------

// One node whose subtree text is exactly known (SPEC 1.6/3: the opening and
// closing tag lines drop with their terminators; the content line keeps its
// terminator).
const T4_3_SPEC_SOURCE = '<S id="a">\nAlpha runtime text.\n</S>\n';
const T4_3_EXPECTED_TEXT = "Alpha runtime text.\n";

// The worked aliased form of TEST-SPEC T4-3, in a discovered code-group file:
// the `t(SPEC.a)` call must record the `embeds` edge (SPEC 4.3), and at
// runtime return the node's subtree text — written to stdout byte-exactly.
// Passing the call's *result* to `process.stdout.write` is unrestricted: the
// 4.5 usage rules bind the spec-module bindings, not the returned string.
const T4_3_CONSUMER_SOURCE = [
  'import SPEC, { text as t } from "../specs/A.xspec";',
  "",
  "process.stdout.write(t(SPEC.a));",
  "",
].join("\n");

const T4_3 = defineProductTest({
  id: "T4-3",
  title:
    'aliased bindings work: `import SPEC, { text as t } from "./NAME.xspec"` type-checks, `t(SPEC.a)` returns the node\'s subtree text at runtime and records the `embeds` edge (SPEC 4, 4.3, 13.1)',
  run: async (product) => {
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      {
        "specs/A.mdx": T4_3_SPEC_SOURCE,
        "src/app.ts": T4_3_CONSUMER_SOURCE,
      },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-3 `build` with the aliased default and `text` bindings",
        );

        // "Records the edge": the top-level call is attributed to the file
        // (SPEC 4.6), and it is the file's complete outgoing edge set.
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/app.ts", "T4-3"),
          [{ from: "src/app.ts", to: "specs/A.mdx#a", kind: "embeds" }],
          "T4-3 `t(SPEC.a)` under aliased bindings records its `embeds` edge " +
            "from the calling code location (SPEC 4.3, 4.6)",
        );

        // "Works" under standard tooling (SPEC 13.1): the aliased bindings
        // type-check, and the compiled consumer run under plain Node writes
        // exactly the node's subtree text.
        const project = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/app.ts"],
        });
        assertNoCompileErrors(
          project,
          "T4-3 consumer with aliased default and `text` bindings",
        );
        const emitted = project.emit();
        if (emitted.emitSkipped) {
          fail(
            "T4-3: consumer emit was skipped; diagnostics:\n" +
              emitted.diagnostics
                .map(
                  (diagnostic) => `  ${formatConsumerDiagnostic(diagnostic)}`,
                )
                .join("\n"),
          );
        }
        const run = await runConsumer({
          dir: workspace.root,
          entry: "src/app.js",
        });
        assertExitCode(
          run,
          0,
          "T4-3 compiled consumer under plain Node (SPEC 13.1)",
        );
        assertBytesEqual(
          run.stdoutBytes,
          T4_3_EXPECTED_TEXT,
          "T4-3 `t(SPEC.a)` at runtime — the node's subtree text (SPEC 4.3, 1.6)",
        );
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T4-4
// ---------------------------------------------------------------------------

const T4_4_SPEC_SOURCE = '<S id="a">\nAlpha behavior.\n</S>\n';

// Both type-only forms (SPEC 4: a `type` modifier on the declaration, and on
// a named binding), then the exact statements that under ordinary bindings
// are a marker and an embedding `text` call. Bindings introduced type-only
// are type-level names: these value-level uses fall under no condition and
// record nothing.
const T4_4_TYPE_ONLY_SOURCE = [
  'import type SPEC from "../specs/A.xspec";',
  'import { type text as t } from "../specs/A.xspec";',
  "",
  "SPEC.a;",
  "t(SPEC.a);",
  "",
].join("\n");

// The control: the same statements under ordinary bindings record their
// `references` (marker, SPEC 4.5) and `embeds` (`text` call, SPEC 4.3) edges.
const T4_4_CONTROL_SOURCE = [
  'import SPEC, { text as t } from "../specs/A.xspec";',
  "",
  "SPEC.a;",
  "t(SPEC.a);",
  "",
].join("\n");

const T4_4 = defineProductTest({
  id: "T4-4",
  title:
    "type-only spec module imports — a `type` modifier on the declaration and on a named binding — are valid; marker-shaped statements and `text` calls rooted at them record no edge and trigger no finding (`build`/`check` exit 0), while the same statements under ordinary bindings record their `references`/`embeds` edges (SPEC 4, 4.5, 14.18)",
  run: async (product) => {
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      {
        "specs/A.mdx": T4_4_SPEC_SOURCE,
        "src/typeonly.ts": T4_4_TYPE_ONLY_SOURCE,
        "src/control.ts": T4_4_CONTROL_SOURCE,
      },
      async (workspace) => {
        // The workspace stays valid: the type-only forms and their
        // value-level uses trigger no xspec finding — not 14.8, not 14.18,
        // none at all (findings are exit-1 outcomes, SPEC 12.0).
        await buildOk(
          product,
          workspace,
          "T4-4 `build` with type-only spec module imports and value-level " +
            "uses rooted at them",
        );
        await expectExit(
          product,
          workspace,
          ["check"],
          0,
          "T4-4 `check` over the same workspace (valid — the consumer-side " +
            "TypeScript error is outside xspec's validations, SPEC 4.5)",
        );

        // No edge leaves the type-only file, however attributed.
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/typeonly.ts", "T4-4"),
          [],
          "T4-4 statements rooted at type-only bindings record no edge " +
            "(SPEC 4, 4.5)",
        );

        // The control records exactly its two edges — and the workspace-wide
        // per-kind sets pin that the type-only file contributed to neither
        // kind anywhere in the graph.
        for (const [kind, meaning] of [
          ["references", "the bare marker `SPEC.a` (SPEC 4.5)"],
          ["embeds", "the `text` call `t(SPEC.a)` (SPEC 4.3)"],
        ] as const) {
          const label = `T4-4 \`query edges --kinds ${kind}\``;
          assertEdgeSetEqual(
            decodeEdgesReport(
              await runJson(
                product,
                workspace,
                ["query", "edges", "--kinds", kind],
                label,
              ),
              label,
            ),
            [{ from: "src/control.ts", to: "specs/A.mdx#a", kind }],
            `${label}: the workspace's complete \`${kind}\` edge set is the ` +
              `control file's edge from ${meaning} — the identical statement ` +
              "under type-only bindings recorded nothing",
          );
        }

        // Under standard tooling (SPEC 13.1): the control compiles clean,
        // grounding the generated module and its skeleton; the type-only
        // file's value-level uses are consumer-side TypeScript errors at the
        // references under test — outside xspec's validations (SPEC 4.5).
        const control = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/control.ts"],
        });
        assertNoCompileErrors(
          control,
          "T4-4 control consumer under ordinary bindings",
        );
        const typeOnly = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/typeonly.ts"],
        });
        assertCompileErrorAt(
          typeOnly,
          typeOnly.locate("src/typeonly.ts", "SPEC.a;"),
          {},
          "T4-4 the marker-shaped statement rooted at the type-only default " +
            "binding — a value-level use of a type-level name is the " +
            "consumer's TypeScript error (SPEC 4, 4.5)",
        );
        assertCompileErrorAt(
          typeOnly,
          typeOnly.locate("src/typeonly.ts", "t(SPEC.a);"),
          {},
          "T4-4 the call rooted at the type-only `text` binding — a " +
            "value-level use of a type-level name is the consumer's " +
            "TypeScript error (SPEC 4, 4.5)",
        );
      },
    );
  },
});

/** TEST-SPEC §4 preamble, in canonical ID order (SUITE-12). */
export const section4Tests: readonly ProductTestEntry[] = [
  T4_1,
  T4_2,
  T4_3,
  T4_4,
];
