// TEST-SPEC §4 preamble (generated TypeScript modules) — SUITE-12:
// T4-1 … T4-4.
//
// Registered product-facing bodies (C-2 "one code path"): each builds its own
// fresh workspace (H-1), drives the product strictly as a subprocess (H-2),
// asserts exact exit codes (H-5), decodes output through the H-3 adapters,
// and rejects a product only via diagnosed assertion failures (H-8).
// Consumer-side contracts — aliased bindings type-checking, `text` at
// runtime, and the type-only value-use TypeScript errors — run under standard
// TypeScript tooling with no xspec runtime dependency (SPEC 13.1) through
// helpers/tooling.ts; consumer files compile and run in CommonJS mode under
// the driver's NodeNext defaults, where the spec-fixed `./NAME.xspec`
// specifier resolves by Node's extension lookup.
//
// SPEC 4: each `NAME.mdx` generates `NAME.xspec.ts` beside it (13.1),
// beginning with a header identifying it as generated by xspec from its
// source file. In a TypeScript file, an import declaration is a spec module
// import exactly when its specifier ends in `.xspec`; the 2.1 specifier form
// and resolution apply and the target must be a discovered spec source
// (14.15); the permitted bindings are the default and `text` exports, each
// optionally aliased, possibly type-only; every other module-linking form
// whose specifier ends in `.xspec` — a dynamic `import()` with a static
// specifier, export declarations in all forms, `import X = require(…)` — is
// invalid (14.15), as is any of the four module-linking forms whose relative
// specifier designates a derived-file path (13.4) other than through
// `.xspec`; a dynamic `import()` with a non-static specifier is not analyzed
// and records nothing; imports colliding on a binding identifier are 14.15
// when either import is a spec module import.
//
// Conservative operationalizations (noted per H-4 — wording is free, so only
// the stated observables are asserted):
// - T4-1 "header": the module's leading comment region — line/block comments
//   (and whitespace) before the first non-comment code. "Mentions the source
//   path" is asserted as containing the source file's name (`NAME.mdx`): the
//   module sits beside its source (13.1), so the name identifies the file and
//   every path rendering — basename, relative, workspace-relative, absolute —
//   contains it.
// - Location assertions: every offending statement in T4-2 is staged at a
//   known byte offset in a pure-ASCII `src/app.ts`, so string indices are
//   byte offsets and each 14.15 finding must fall within the offending
//   statement's own byte window (end-widened by one byte for line-granular
//   locations, support.ts byteWindow).
// - T4-2 "no occurrence": the side-effect-only import's positive arm compares
//   the `occurrences` document's complete (file, kind, target) multiset with
//   the two ordinary consumers' records — a phantom record is an extra tuple
//   — leaving each record's source datum and exact span to T5.7-2/T5.7-3.

import type {
  DependencyEdgeKind,
  Finding,
  GraphEdge,
  OccurrenceRecord,
} from "../../helpers/adapters/index.js";
import {
  decodeEdgesReport,
  decodeFindingsReport,
  decodeOccurrencesReport,
  renderPathValue,
} from "../../helpers/adapters/index.js";
import {
  assertBytesEqual,
  assertExitCode,
  fail,
  parseJsonStdout,
} from "../../helpers/assertions.js";
import { defineProductTest } from "../../helpers/registry.js";
import type { ProductTestEntry } from "../../helpers/registry.js";
import { stagedMdx } from "../../helpers/staged-mdx.js";
import type { ProductBinding } from "../../helpers/subprocess.js";
import {
  assertCompileErrorAt,
  assertNoCompileErrors,
  ConsumerProject,
  formatConsumerDiagnostic,
  runConsumer,
} from "../../helpers/tooling.js";
import { TestWorkspace } from "../../helpers/workspace.js";
import type { InitialFileContents } from "../../helpers/workspace.js";
import {
  assertConditionCounts,
  assertEdgeSetEqual,
  assertFindingLocated,
  assertFindingLocatesExactly,
  assertSameJson,
  buildFindings,
  buildOk,
  byteWindow,
  expectExit,
  readGeneratedModule,
  runJson,
  stageBesideRoot,
} from "./support.js";

// Minimal declarative configuration (SPEC 7): exactly one spec group.
const SPECS_ONLY_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  }
})
`;

// One spec group plus one code group (SPEC 7.2): TypeScript files under
// `src/` are discovered code sources, so `build` analyzes their imports and
// spec-module usage (4, 4.5).
const SPEC_AND_CODE_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  }
})
`;

// The same plus enabled Markdown emission, for the T4-2 arms whose derived
// path is a configured Markdown emit destination — those exist exactly while
// emission is enabled (SPEC 7.3), with the default next-to-source placement.
const MARKDOWN_EMIT_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  },
  markdown: { emit: true }
})
`;

// A spec group reaching `.mdx` files under `src/`, beside the code group's
// `.ts` files (SPEC 7.1, 7.2: the two globs match disjoint sets; the
// generated `src/NAME.xspec.ts` is a derived file, excluded from every group,
// 13.4), for the T4-2 arms whose specifier TEST-SPEC pins relative to the
// spec source's own directory — the lexical positives and the escape-spelled
// name segment.
const COLOCATED_CONFIG = `import { defineConfig } from "xspec"

export default defineConfig({
  specs: {
    main: ["specs/**/*.mdx", "src/**/*.mdx"]
  },
  code: {
    app: ["src/**/*.ts"]
  }
})
`;

/** Stage a fresh workspace (config plus `files`), run `body`, dispose (H-1). */
async function withWorkspace<T>(
  config: string,
  files: Readonly<Record<string, InitialFileContents>>,
  body: (workspace: TestWorkspace) => Promise<T>,
): Promise<T> {
  const workspace = await TestWorkspace.create({
    files: { "xspec.config.ts": config, ...files },
  });
  try {
    return await body(workspace);
  } finally {
    await workspace.dispose();
  }
}

/** `query edges --from <graph-node>`, decoded (SPEC 11). */
async function queryEdgesFrom(
  product: ProductBinding,
  workspace: TestWorkspace,
  from: string,
  context: string,
): Promise<readonly GraphEdge[]> {
  const label = `${context} \`query edges --from ${from}\``;
  return decodeEdgesReport(
    await runJson(
      product,
      workspace,
      ["query", "edges", "--from", from],
      label,
    ),
    label,
  );
}

// ---------------------------------------------------------------------------
// T4-1
// ---------------------------------------------------------------------------

// Two spec sources with distinct names, one in a subdirectory, so each
// generated module's header must identify its *own* source file — a constant
// header copied between modules fails the per-module name assertion.
const T4_1_FILES = {
  "specs/A.mdx": '<S id="alpha">\nAlpha behavior.\n</S>\n',
  "specs/sub/B.mdx": '<S id="beta">\nBeta behavior.\n</S>\n',
} as const;

/**
 * The module's leading comment region: line and block comments, with
 * interleaving whitespace, from the start of the file up to the first
 * non-comment code. An unterminated block comment does not extend the
 * region (it is not a well-formed header).
 */
function leadingCommentRegion(moduleText: string): string {
  let at = 0;
  let end = 0;
  while (at < moduleText.length) {
    if (/\s/.test(moduleText[at]!)) {
      at += 1;
      continue;
    }
    if (moduleText.startsWith("//", at)) {
      const lineEnd = moduleText.indexOf("\n", at);
      at = lineEnd === -1 ? moduleText.length : lineEnd + 1;
      end = at;
      continue;
    }
    if (moduleText.startsWith("/*", at)) {
      const close = moduleText.indexOf("*/", at + 2);
      if (close === -1) break;
      at = close + 2;
      end = at;
      continue;
    }
    break;
  }
  return moduleText.slice(0, end);
}

const T4_1 = defineProductTest({
  id: "T4-1",
  title:
    "each generated module begins with a header identifying it as generated by xspec from its source file — header present, mentions xspec and the source file, wording free (SPEC 4, 13.1)",
  run: async (product) => {
    await withWorkspace(SPECS_ONLY_CONFIG, T4_1_FILES, async (workspace) => {
      await buildOk(product, workspace, "T4-1 `build` over two spec sources");
      for (const [modulePath, sourceName] of [
        ["specs/A.xspec.ts", "A.mdx"],
        ["specs/sub/B.xspec.ts", "B.mdx"],
      ] as const) {
        const context = `T4-1 generated module ${modulePath}`;
        const moduleText = await readGeneratedModule(
          workspace,
          modulePath,
          context,
        );
        const header = leadingCommentRegion(moduleText);
        if (header === "") {
          fail(
            `${context}: the module must begin with a header — a comment region ` +
              `before any code (SPEC 4: "MUST begin with a header"); the module ` +
              `starts with ${JSON.stringify(moduleText.slice(0, 120))}`,
          );
        }
        if (!/xspec/i.test(header)) {
          fail(
            `${context}: the header must identify the module as generated by ` +
              `xspec (SPEC 4) — "xspec" does not appear in the leading comment ` +
              `region: ${JSON.stringify(header)}`,
          );
        }
        if (!header.includes(sourceName)) {
          fail(
            `${context}: the header must identify the module's source file ` +
              `(SPEC 4: "from its source file") — expected the leading comment ` +
              `region to mention ${JSON.stringify(sourceName)} (every rendering ` +
              `of the source path contains the file name); got ` +
              JSON.stringify(header),
          );
        }
      }
    });
  },
});

// ---------------------------------------------------------------------------
// T4-2
// ---------------------------------------------------------------------------

// Every arm's workspace: the configuration, a valid discovered spec source
// `specs/BASE.mdx` (so arms whose specifier names it carry the specifier or
// binding form as their only defect), any arm-specific extra files, and
// `src/app.ts` holding exactly the arm's statements — the offending
// construct(s) start at byte 0, everything pure ASCII. Every arm's workspace
// past the first is created after a product invocation, so its `.mdx` entries
// — the shared base and an arm's extras alike — are staged-source records,
// judged before any product exists (S-9, test/self/s9-staged-sources.test.ts).
const T4_2_BASE_FILES = {
  "specs/BASE.mdx": stagedMdx(
    "T4-2 specs/BASE.mdx",
    '<S id="core">\nCore behavior.\n</S>\n',
  ),
} as const;

// The spec source the colocated arms discover beside the code files
// (COLOCATED_CONFIG): `src/NAME.mdx`, one node `core` — staged by the
// escape-spelled arm and the lexical positives.
const COLOCATED_SPEC_SOURCE = stagedMdx(
  "T4-2 src/NAME.mdx",
  '<S id="core">\nCore behavior.\n</S>\n',
);

// The escape character, built from its code point so that no tool layer
// decodes the six-character escape spelling staged below on its way into the
// file (the pattern of section-1.4.ts).
const BACKSLASH = String.fromCodePoint(0x5c);

/** One invalid TS import-rule arm: a workspace differing only in src/app.ts. */
interface InvalidTsImportArm {
  /** Which SPEC 4 invalid case this is (failure diagnostics). */
  readonly name: string;
  /** The statements of `src/app.ts`, staged one per line from byte 0. */
  readonly statements: readonly string[];
  /**
   * Upper bound on accepted 14.15 findings. Duplicate-binding arms accept 2:
   * SPEC 2.1/14.15 define one condition over the colliding pair, and whether
   * a product reports the collision once or per import is not fixed.
   */
  readonly maxFindings?: number;
  /** Configuration override (defaults to SPEC_AND_CODE_CONFIG). */
  readonly config?: string;
  /** Files staged beside the base files. */
  readonly extraFiles?: Readonly<Record<string, InitialFileContents>>;
  /**
   * Files staged OUTSIDE the workspace root, at paths relative to the root's
   * parent directory (support.ts stageBesideRoot) — the above-root arm's real
   * `outside/NAME.mdx`, which resolution must never reach (SPEC 2.1, 4).
   */
  readonly outsideFiles?: Readonly<Record<string, string>>;
}

// The `.xspec`-specifier rules (SPEC 4: target must be a discovered spec
// source; the 2.1 specifier form applies in TS; only the default and `text`
// exports may be bound; no other module-linking form may carry a `.xspec`
// specifier).
const XSPEC_RULE_ARMS: readonly InvalidTsImportArm[] = [
  {
    name: "a `.xspec` specifier designating an existing file that is not a discovered spec source",
    statements: ['import MOD from "../docs/EXTRA.xspec";'],
    extraFiles: {
      "docs/EXTRA.mdx": stagedMdx(
        "T4-2 arm undiscovered existing file docs/EXTRA.mdx",
        '<S id="extra">\nOutside every spec group.\n</S>\n',
      ),
    },
  },
  {
    name: "a `.xspec` specifier designating a nonexistent file",
    statements: ['import MOD from "../specs/missing.xspec";'],
  },
  {
    name: "a bare specifier ending `.xspec`",
    statements: ['import MOD from "BASE.xspec";'],
  },
  {
    name: "an absolute specifier ending `.xspec`",
    statements: ['import MOD from "/specs/BASE.xspec";'],
  },
  {
    // From `src/` (depth 1) the two `..` segments reach depth -1: the ascent
    // passes above the workspace root, so the specifier designates nothing
    // (SPEC 2.1, 4) although the root's parent really holds
    // `outside/NAME.mdx` — the discriminator against filesystem resolution.
    name: "a `.xspec` specifier whose ascent passes above the workspace root, the root's parent holding a real `outside/NAME.mdx`",
    statements: ['import MOD from "../../outside/NAME.xspec";'],
    outsideFiles: {
      "outside/NAME.mdx": '<S id="core">\nCore behavior, outside.\n</S>\n',
    },
  },
  {
    // The six-character escape of `A` in the name segment is read verbatim
    // (SPEC 2.4): the segment spells a name containing the escape character,
    // which no discovered path spells. `src/NAME.mdx` is a discovered spec
    // source beside the code file (COLOCATED_CONFIG), so a product
    // interpreting the escape resolves the import, builds clean, and fails
    // the arm.
    name: `a \`.xspec\` specifier spelled with an escape sequence in a name segment ("./N${BACKSLASH}u0041ME.xspec"), read verbatim`,
    statements: [`import MOD from "./N${BACKSLASH}u0041ME.xspec";`],
    config: COLOCATED_CONFIG,
    extraFiles: { "src/NAME.mdx": COLOCATED_SPEC_SOURCE },
  },
  {
    name: "a named binding other than `text`",
    statements: ['import { core } from "../specs/BASE.xspec";'],
  },
  {
    name: "a namespace binding",
    statements: ['import * as NS from "../specs/BASE.xspec";'],
  },
  {
    name: "a dynamic `import()` with a static `.xspec` specifier",
    statements: ['void import("../specs/BASE.xspec");'],
  },
  {
    name: "an `export * from` declaration with a `.xspec` specifier",
    statements: ['export * from "../specs/BASE.xspec";'],
  },
  {
    name: "an `export * as NS from` declaration with a `.xspec` specifier",
    statements: ['export * as NS from "../specs/BASE.xspec";'],
  },
  {
    // Even the permitted-binding name is not re-exportable: no re-export
    // carries a spec module's nodes or `text` past 4.5.
    name: "an `export { … } from` declaration with a `.xspec` specifier",
    statements: ['export { text } from "../specs/BASE.xspec";'],
  },
  {
    name: "a type-only `export type { … } from` declaration with a `.xspec` specifier",
    statements: ['export type { text } from "../specs/BASE.xspec";'],
  },
  {
    name: "an `import X = require(…)` declaration with a `.xspec` specifier",
    statements: ['import MOD = require("../specs/BASE.xspec");'],
  },
];

// The side-effect-only form (SPEC 4): `import "./NAME.xspec"` binds nothing,
// records nothing, and is valid in a code-group file (the positive arm
// below) — "its specifier held to the rule above like any other's" — so the
// two specifier defects TEST-SPEC pins fail with 14.15 through it: a `.xspec`
// specifier designating no discovered spec source (`./missing.xspec`
// designates `src/missing.mdx`, no such file), and a relative specifier
// designating a derived-file path (`../specs/BASE.xspec.ts`, a file name
// containing `.xspec.`, 13.4) without being a spec module import.
const SIDE_EFFECT_IMPORT_ARMS: readonly InvalidTsImportArm[] = [
  {
    name: 'a side-effect-only import whose `.xspec` specifier designates a nonexistent file (`import "./missing.xspec"`)',
    statements: ['import "./missing.xspec";'],
  },
  {
    name: 'a side-effect-only import whose relative specifier designates a derived-file path (`import "../specs/BASE.xspec.ts"`)',
    statements: ['import "../specs/BASE.xspec.ts";'],
  },
];

// Derived-path arms (SPEC 4, 13.4): the full cross product of the four
// module-linking forms SPEC 4 names and the three derived-file path kinds of
// 13.4 — a file name containing `.xspec.` (the generated module's own path,
// consumed only through its `.xspec` specifier), a path under `.xspec/`, and
// a configured Markdown emit destination (a derived path exactly while
// emission is enabled, whether or not emission has yet run, SPEC 7.3 — so
// those arms run under MARKDOWN_EMIT_CONFIG). The classification is by path
// (13.4), so no file needs to exist at the specifier's target.
const MODULE_LINKING_FORMS: readonly {
  readonly form: string;
  readonly statement: (specifier: string) => string;
}[] = [
  {
    form: "an import declaration",
    statement: (specifier) => `import MOD from "${specifier}";`,
  },
  {
    form: "an export declaration",
    statement: (specifier) => `export * from "${specifier}";`,
  },
  {
    form: "an `import X = require(…)` declaration",
    statement: (specifier) => `import MOD = require("${specifier}");`,
  },
  {
    form: "a static-specifier dynamic `import()`",
    statement: (specifier) => `void import("${specifier}");`,
  },
];

const DERIVED_PATH_KINDS: readonly {
  readonly kind: string;
  readonly specifier: string;
  readonly config?: string;
}[] = [
  {
    kind: "a file name containing `.xspec.` (`../specs/BASE.xspec.ts` directly)",
    specifier: "../specs/BASE.xspec.ts",
  },
  {
    kind: "a path under `.xspec/`",
    specifier: "../.xspec/data.ts",
  },
  {
    kind: "a configured Markdown emit destination (emission enabled)",
    specifier: "../specs/BASE.md",
    config: MARKDOWN_EMIT_CONFIG,
  },
];

const DERIVED_PATH_ARMS: readonly InvalidTsImportArm[] =
  MODULE_LINKING_FORMS.flatMap((form) =>
    DERIVED_PATH_KINDS.map((path) => ({
      name: `${form.form} whose relative specifier designates ${path.kind}`,
      statements: [form.statement(path.specifier)],
      config: path.config,
    })),
  );

// Duplicate-binding arms (SPEC 4, 2.1, 14.15 — "in either kind of file"; the
// MDX side is T2.1-3's): a collision fails when either import is a spec
// module import — spec with spec, and spec with non-spec in both orders.
const DUPLICATE_BINDING_ARMS: readonly InvalidTsImportArm[] = [
  {
    name: "two spec module imports binding one identifier",
    statements: [
      'import MOD from "../specs/BASE.xspec";',
      'import MOD from "../specs/OTHER.xspec";',
    ],
    extraFiles: {
      "specs/OTHER.mdx": stagedMdx(
        "T4-2 arm two spec module imports binding one identifier specs/OTHER.mdx",
        '<S id="other">\nOther behavior.\n</S>\n',
      ),
    },
    maxFindings: 2,
  },
  {
    name: "a spec module import colliding with a later non-spec import",
    statements: [
      'import MOD from "../specs/BASE.xspec";',
      'import MOD from "node:path";',
    ],
    maxFindings: 2,
  },
  {
    name: "a non-spec import colliding with a later spec module import",
    statements: [
      'import MOD from "node:path";',
      'import MOD from "../specs/BASE.xspec";',
    ],
    maxFindings: 2,
  },
];

/**
 * Run one invalid-import arm: `build --json` exits 1 with only 14.15
 * findings — exactly one for a single-statement arm, one or two for a
 * colliding pair — each locating the importing code file and falling within
 * an offending statement's own byte window (SPEC 14: errors identify file
 * and location).
 */
async function runInvalidTsImportArm(
  product: ProductBinding,
  arm: InvalidTsImportArm,
  testId: string,
): Promise<void> {
  const context = `${testId} \`build --json\` over ${arm.name}`;
  const windows: { start: number; end: number }[] = [];
  let prefix = "";
  for (const statement of arm.statements) {
    windows.push(byteWindow(prefix, statement));
    prefix += statement + "\n";
  }
  await withWorkspace(
    arm.config ?? SPEC_AND_CODE_CONFIG,
    {
      ...T4_2_BASE_FILES,
      ...arm.extraFiles,
      "src/app.ts": prefix,
    },
    async (workspace) => {
      await stageBesideRoot(workspace, arm.outsideFiles ?? {});
      const findings = await buildFindings(product, workspace, context);
      const max = arm.maxFindings ?? 1;
      if (max === 1) {
        assertConditionCounts(findings, { "14.15": 1 }, context);
        assertFindingLocated(
          findings[0]!,
          { file: "src/app.ts", window: windows[0]! },
          `${context}: the 14.15 finding`,
        );
        return;
      }
      const conditions = findings.map((finding) => finding.condition);
      if (
        findings.length < 1 ||
        findings.length > max ||
        conditions.some((condition) => condition !== "14.15")
      ) {
        fail(
          `${context}: expected the colliding pair to report condition 14.15 — ` +
            `one finding for the collision, or one per import — got ` +
            JSON.stringify(conditions),
        );
      }
      for (const finding of findings) {
        const findingContext = `${context}: a 14.15 finding`;
        assertFindingLocated(finding, { file: "src/app.ts" }, findingContext);
        for (const { range } of finding.locations) {
          const within = windows.some(
            (window) => range.start >= window.start && range.end <= window.end,
          );
          if (!within) {
            fail(
              `${findingContext}: every location [${String(range.start)}, ` +
                `${String(range.end)}) must point at one of the colliding ` +
                `import statements (byte windows ${JSON.stringify(windows)})`,
            );
          }
        }
      }
    },
  );
}

// Positive arm: a dynamic `import()` with a non-static specifier is not
// analyzed. The identifier holds a string that *would* designate the
// discovered spec source — a product that analyzed the call (e.g. by constant
// propagation) would have to report the always-invalid static-specifier
// dynamic import (14.15) and fail the exit-0 expectation; a conforming
// product records nothing from the file.
const NON_STATIC_DYNAMIC_SOURCE = [
  'const target = "../specs/BASE.xspec";',
  "void import(target);",
  "",
].join("\n");

// Positive arm: two colliding non-spec imports — neither is a spec module
// import, so the collision is no xspec finding, and the unused colliding
// bindings trigger no xspec error (TypeScript's own complaint is outside
// xspec's validations).
const NON_SPEC_COLLISION_SOURCE = [
  'import MOD from "node:path";',
  'import MOD from "node:url";',
  "",
].join("\n");

// Positive arms: lexical resolution in TS (SPEC 4: the resolution of 2.1).
// The spec source `src/NAME.mdx` sits beside its consumers under
// COLOCATED_CONFIG, and the workspace holds no `src/sub/` at all, so
// `./sub/../NAME.xspec` resolves only lexically; `.//NAME.xspec` spells the
// same directory through an empty segment. Each consumer's bare marker
// records a `references` edge to the resolved node (4.5): a product failing
// to resolve either spelling reports 14.15 and fails the build, and one
// resolving it elsewhere records the wrong edge target.
const LEXICAL_TS_CONSUMERS: readonly {
  readonly file: string;
  readonly specifier: string;
}[] = [
  { file: "src/one.ts", specifier: "./sub/../NAME.xspec" },
  { file: "src/two.ts", specifier: ".//NAME.xspec" },
];

function lexicalTsConsumerSource(specifier: string): string {
  return [`import NAME from "${specifier}";`, "", "NAME.core;", ""].join("\n");
}

// Positive arm: a side-effect-only import in a code-group file (SPEC 4: it
// binds nothing, records nothing, and is valid). It is staged alone in
// `src/side.ts` beside two ordinary consumers — a bare marker (`references`,
// 4.5) and a `text(...)` call (`embeds`, 4.3) — so both consulted surfaces
// are live: the consumers' edges and occurrences are the workspace's only
// ones, and a product that treats the side-effect form as an import defect
// (14.15 at `build` or `check`) or records anything from it is caught — an
// edge by `query edges --from src/side.ts`, a phantom occurrence as an extra
// tuple in the exact (file, kind, target) multiset (SPEC 5.7: an import
// declaration, its binding used or not, records no occurrence).
const SIDE_EFFECT_IMPORT_FILE = "src/side.ts";
const SIDE_EFFECT_IMPORT_SOURCE = 'import "../specs/BASE.xspec";\n';

const SIDE_EFFECT_ORDINARY_CONSUMERS: Readonly<Record<string, string>> = {
  "src/one.ts": [
    'import BASE from "../specs/BASE.xspec";',
    "",
    "BASE.core;",
    "",
  ].join("\n"),
  "src/two.ts": [
    'import BASE, { text } from "../specs/BASE.xspec";',
    "",
    "process.stdout.write(text(BASE.core));",
    "",
  ].join("\n"),
};

// The consumers' edges (SPEC 4.3, 4.5; top-level statements, so each source
// node is the code file itself) and, behind them, the workspace's complete
// occurrence multiset as (file, kind, target) units (SPEC 5.7).
const SIDE_EFFECT_CONSUMER_EDGES: readonly {
  readonly from: string;
  readonly to: string;
  readonly kind: DependencyEdgeKind;
}[] = [
  { from: "src/one.ts", to: "specs/BASE.mdx#core", kind: "references" },
  { from: "src/two.ts", to: "specs/BASE.mdx#core", kind: "embeds" },
];

function renderOccurrenceTriple(
  file: string,
  kind: DependencyEdgeKind,
  target: string,
): string {
  return `${file} [${kind}] -> ${target}`;
}

const T4_2 = defineProductTest({
  id: "T4-2",
  title: `TS import rules: undiscovered/nonexistent/bare/absolute \`.xspec\` specifiers, one whose ascent passes above the root (a real \`outside/NAME.mdx\` at the root's parent), one escape-spelled in a name segment ("./N${BACKSLASH}u0041ME.xspec", read verbatim), bindings other than the default and \`text\`, static-specifier dynamic \`import()\`, every export-declaration form, \`import X = require(…)\`, and derived-path specifiers through each module-linking form all fail with 14.15; \`./sub/../NAME.xspec\` (no \`sub/\` on disk) and \`.//NAME.xspec\` resolve lexically to NAME.mdx and markers through them record edges; a non-static dynamic \`import()\` is not analyzed; binding collisions are 14.15 when either import is a spec module import, and no finding otherwise; a side-effect-only \`import "./NAME.xspec"\` binds nothing and is valid in a code-group file — \`build\` and \`check\` exit 0, no edge, no occurrence — while \`import "./missing.xspec"\` and \`import "../specs/NAME.xspec.ts"\` fail with 14.15 (SPEC 4, 2.1, 2.4, 5.7, 13.4, 14.15)`,
  // Many small workspaces (31 negative arms plus four positive ones), each
  // one product invocation or a few: a wider hang budget than the default
  // (H-8 hang guard only, never an assertion — H-10).
  timeoutMs: 240_000,
  run: async (product) => {
    for (const arm of [
      ...XSPEC_RULE_ARMS,
      ...SIDE_EFFECT_IMPORT_ARMS,
      ...DERIVED_PATH_ARMS,
      ...DUPLICATE_BINDING_ARMS,
    ]) {
      await runInvalidTsImportArm(product, arm, "T4-2");
    }

    // Lexical positives: `./sub/../NAME.xspec` (no src/sub/ on disk) and
    // `.//NAME.xspec` resolve to src/NAME.mdx; the markers record edges.
    await withWorkspace(
      COLOCATED_CONFIG,
      {
        ...T4_2_BASE_FILES,
        "src/NAME.mdx": COLOCATED_SPEC_SOURCE,
        ...Object.fromEntries(
          LEXICAL_TS_CONSUMERS.map((consumer) => [
            consumer.file,
            lexicalTsConsumerSource(consumer.specifier),
          ]),
        ),
      },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-2 `build` with `./sub/../NAME.xspec` (no src/sub/ on disk) " +
            "and `.//NAME.xspec` imported by code files beside src/NAME.mdx " +
            "— each resolves lexically to the discovered spec source " +
            "(SPEC 4, 2.1)",
        );
        for (const consumer of LEXICAL_TS_CONSUMERS) {
          assertEdgeSetEqual(
            await queryEdgesFrom(product, workspace, consumer.file, "T4-2"),
            [
              {
                from: consumer.file,
                to: "src/NAME.mdx#core",
                kind: "references",
              },
            ],
            `T4-2 the marker through \`${consumer.specifier}\` records its ` +
              "`references` edge to src/NAME.mdx#core — the specifier " +
              "resolved lexically (SPEC 4, 2.1, 4.5)",
          );
        }
      },
    );

    // Side-effect-only import: valid in a code-group file beside ordinary
    // consumers — `build` and `check` exit 0, no edge, no occurrence.
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      {
        ...T4_2_BASE_FILES,
        [SIDE_EFFECT_IMPORT_FILE]: SIDE_EFFECT_IMPORT_SOURCE,
        ...SIDE_EFFECT_ORDINARY_CONSUMERS,
      },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          'T4-2 `build` with a side-effect-only `import "../specs/BASE.xspec"` ' +
            "alone in src/side.ts beside two ordinary consumers (SPEC 4: the " +
            "form binds nothing and is valid in a code-group file)",
        );
        await expectExit(
          product,
          workspace,
          ["check"],
          0,
          "T4-2 `check` over the same workspace (SPEC 4: the side-effect-only " +
            "import is valid)",
        );
        assertEdgeSetEqual(
          await queryEdgesFrom(
            product,
            workspace,
            SIDE_EFFECT_IMPORT_FILE,
            "T4-2",
          ),
          [],
          "T4-2 the side-effect-only import records no edge: none leaves " +
            "src/side.ts (SPEC 4)",
        );
        for (const edge of SIDE_EFFECT_CONSUMER_EDGES) {
          assertEdgeSetEqual(
            await queryEdgesFrom(product, workspace, edge.from, "T4-2"),
            [edge],
            `T4-2 the ordinary consumer ${edge.from} beside it records its ` +
              `\`${edge.kind}\` edge (SPEC 4.3, 4.5) — the edge surface is live`,
          );
        }
        const context = "T4-2 `occurrences`";
        const report = decodeOccurrencesReport(
          await runJson(product, workspace, ["occurrences"], context),
          context,
        );
        if (report.findings.length !== 0) {
          fail(
            `${context}: the valid workspace consults finding-free (SPEC 11.2) ` +
              `— got ${JSON.stringify(report.findings.map((finding) => finding.condition ?? finding.code))}`,
          );
        }
        const actual = report.occurrences
          .map((record) =>
            renderOccurrenceTriple(
              renderPathValue(record.file),
              record.kind,
              record.target,
            ),
          )
          .sort();
        const expected = SIDE_EFFECT_CONSUMER_EDGES.map((edge) =>
          renderOccurrenceTriple(edge.from, edge.kind, edge.to),
        ).sort();
        if (JSON.stringify(actual) !== JSON.stringify(expected)) {
          fail(
            `${context}: the workspace's occurrences are exactly the two ` +
              `ordinary consumers' — the side-effect-only import records none ` +
              `(SPEC 4, 5.7); expected ${JSON.stringify(expected)}, got ` +
              JSON.stringify(actual),
          );
        }
      },
    );

    // Non-static dynamic import: build succeeds, no edges recorded.
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      { ...T4_2_BASE_FILES, "src/app.ts": NON_STATIC_DYNAMIC_SOURCE },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-2 `build` with a dynamic `import()` whose specifier is a " +
            "non-static expression (an identifier)",
        );
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/app.ts", "T4-2"),
          [],
          "T4-2 a non-static dynamic `import()` is not analyzed: no edge " +
            "leaves the code file (SPEC 4)",
        );
      },
    );

    // Two colliding non-spec imports: not an xspec finding.
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      { ...T4_2_BASE_FILES, "src/app.ts": NON_SPEC_COLLISION_SOURCE },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-2 `build` with two colliding non-spec imports (no spec module " +
            "import participates, so no xspec finding — SPEC 4, 14.15)",
        );
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T4-3
// ---------------------------------------------------------------------------

// One node whose subtree text is exactly known (SPEC 1.6/3: the opening and
// closing tag lines drop with their terminators; the content line keeps its
// terminator).
const T4_3_SPEC_SOURCE = '<S id="a">\nAlpha runtime text.\n</S>\n';
const T4_3_EXPECTED_TEXT = "Alpha runtime text.\n";

// The worked aliased form of TEST-SPEC T4-3, in a discovered code-group file:
// the `t(SPEC.a)` call must record the `embeds` edge (SPEC 4.3), and at
// runtime return the node's subtree text — written to stdout byte-exactly.
// Passing the call's *result* to `process.stdout.write` is unrestricted: the
// 4.5 usage rules bind the spec-module bindings, not the returned string.
const T4_3_CONSUMER_SOURCE = [
  'import SPEC, { text as t } from "../specs/A.xspec";',
  "",
  "process.stdout.write(t(SPEC.a));",
  "",
].join("\n");

const T4_3 = defineProductTest({
  id: "T4-3",
  title:
    'aliased bindings work: `import SPEC, { text as t } from "./NAME.xspec"` type-checks, `t(SPEC.a)` returns the node\'s subtree text at runtime and records the `embeds` edge (SPEC 4, 4.3, 13.1)',
  run: async (product) => {
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      {
        "specs/A.mdx": T4_3_SPEC_SOURCE,
        "src/app.ts": T4_3_CONSUMER_SOURCE,
      },
      async (workspace) => {
        await buildOk(
          product,
          workspace,
          "T4-3 `build` with the aliased default and `text` bindings",
        );

        // "Records the edge": the top-level call is attributed to the file
        // (SPEC 4.6), and it is the file's complete outgoing edge set.
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/app.ts", "T4-3"),
          [{ from: "src/app.ts", to: "specs/A.mdx#a", kind: "embeds" }],
          "T4-3 `t(SPEC.a)` under aliased bindings records its `embeds` edge " +
            "from the calling code location (SPEC 4.3, 4.6)",
        );

        // "Works" under standard tooling (SPEC 13.1): the aliased bindings
        // type-check, and the compiled consumer run under plain Node writes
        // exactly the node's subtree text.
        const project = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/app.ts"],
        });
        assertNoCompileErrors(
          project,
          "T4-3 consumer with aliased default and `text` bindings",
        );
        const emitted = project.emit();
        if (emitted.emitSkipped) {
          fail(
            "T4-3: consumer emit was skipped; diagnostics:\n" +
              emitted.diagnostics
                .map(
                  (diagnostic) => `  ${formatConsumerDiagnostic(diagnostic)}`,
                )
                .join("\n"),
          );
        }
        const run = await runConsumer({
          dir: workspace.root,
          entry: "src/app.js",
        });
        assertExitCode(
          run,
          0,
          "T4-3 compiled consumer under plain Node (SPEC 13.1)",
        );
        assertBytesEqual(
          run.stdoutBytes,
          T4_3_EXPECTED_TEXT,
          "T4-3 `t(SPEC.a)` at runtime — the node's subtree text (SPEC 4.3, 1.6)",
        );
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T4-4
// ---------------------------------------------------------------------------

const T4_4_SPEC_SOURCE = '<S id="a">\nAlpha behavior.\n</S>\n';

// Both type-only forms (SPEC 4: a `type` modifier on the declaration, and on
// a named binding), then the exact statements that under ordinary bindings
// are a marker and an embedding `text` call. Bindings introduced type-only
// are type-level names: these value-level uses fall under no condition and
// record nothing.
const T4_4_TYPE_ONLY_SOURCE = [
  'import type SPEC from "../specs/A.xspec";',
  'import { type text as t } from "../specs/A.xspec";',
  "",
  "SPEC.a;",
  "t(SPEC.a);",
  "",
].join("\n");

// The control: the same statements under ordinary bindings record their
// `references` (marker, SPEC 4.5) and `embeds` (`text` call, SPEC 4.3) edges.
const T4_4_CONTROL_SOURCE = [
  'import SPEC, { text as t } from "../specs/A.xspec";',
  "",
  "SPEC.a;",
  "t(SPEC.a);",
  "",
].join("\n");

const T4_4 = defineProductTest({
  id: "T4-4",
  title:
    "type-only spec module imports — a `type` modifier on the declaration and on a named binding — are valid; marker-shaped statements and `text` calls rooted at them record no edge and trigger no finding (`build`/`check` exit 0), while the same statements under ordinary bindings record their `references`/`embeds` edges (SPEC 4, 4.5, 14.18)",
  run: async (product) => {
    await withWorkspace(
      SPEC_AND_CODE_CONFIG,
      {
        "specs/A.mdx": T4_4_SPEC_SOURCE,
        "src/typeonly.ts": T4_4_TYPE_ONLY_SOURCE,
        "src/control.ts": T4_4_CONTROL_SOURCE,
      },
      async (workspace) => {
        // The workspace stays valid: the type-only forms and their
        // value-level uses trigger no xspec finding — not 14.8, not 14.18,
        // none at all (findings are exit-1 outcomes, SPEC 12.0).
        await buildOk(
          product,
          workspace,
          "T4-4 `build` with type-only spec module imports and value-level " +
            "uses rooted at them",
        );
        await expectExit(
          product,
          workspace,
          ["check"],
          0,
          "T4-4 `check` over the same workspace (valid — the consumer-side " +
            "TypeScript error is outside xspec's validations, SPEC 4.5)",
        );

        // No edge leaves the type-only file, however attributed.
        assertEdgeSetEqual(
          await queryEdgesFrom(product, workspace, "src/typeonly.ts", "T4-4"),
          [],
          "T4-4 statements rooted at type-only bindings record no edge " +
            "(SPEC 4, 4.5)",
        );

        // The control records exactly its two edges — and the workspace-wide
        // per-kind sets pin that the type-only file contributed to neither
        // kind anywhere in the graph.
        for (const [kind, meaning] of [
          ["references", "the bare marker `SPEC.a` (SPEC 4.5)"],
          ["embeds", "the `text` call `t(SPEC.a)` (SPEC 4.3)"],
        ] as const) {
          const label = `T4-4 \`query edges --kinds ${kind}\``;
          assertEdgeSetEqual(
            decodeEdgesReport(
              await runJson(
                product,
                workspace,
                ["query", "edges", "--kinds", kind],
                label,
              ),
              label,
            ),
            [{ from: "src/control.ts", to: "specs/A.mdx#a", kind }],
            `${label}: the workspace's complete \`${kind}\` edge set is the ` +
              `control file's edge from ${meaning} — the identical statement ` +
              "under type-only bindings recorded nothing",
          );
        }

        // Under standard tooling (SPEC 13.1): the control compiles clean,
        // grounding the generated module and its skeleton; the type-only
        // file's value-level uses are consumer-side TypeScript errors at the
        // references under test — outside xspec's validations (SPEC 4.5).
        const control = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/control.ts"],
        });
        assertNoCompileErrors(
          control,
          "T4-4 control consumer under ordinary bindings",
        );
        const typeOnly = await ConsumerProject.load({
          rootDir: workspace.root,
          rootFiles: ["src/typeonly.ts"],
        });
        assertCompileErrorAt(
          typeOnly,
          typeOnly.locate("src/typeonly.ts", "SPEC.a;"),
          {},
          "T4-4 the marker-shaped statement rooted at the type-only default " +
            "binding — a value-level use of a type-level name is the " +
            "consumer's TypeScript error (SPEC 4, 4.5)",
        );
        assertCompileErrorAt(
          typeOnly,
          typeOnly.locate("src/typeonly.ts", "t(SPEC.a);"),
          {},
          "T4-4 the call rooted at the type-only `text` binding — a " +
            "value-level use of a type-level name is the consumer's " +
            "TypeScript error (SPEC 4, 4.5)",
        );
      },
    );
  },
});

// ---------------------------------------------------------------------------
// T4-5
// ---------------------------------------------------------------------------

// Two spec sources — `A`, the module every arm's chains name (`SPEC.a`,
// `text(SPEC.b)`), and `B`, the second spec module the first pairing's
// type-only import designates — plus `src/t.ts`, the non-spec module `./t`
// the other pairings import: a discovered code source recording nothing,
// exporting a value `SPEC` so that each non-spec import designates a real
// binding (consumer-side resolution is outside xspec's validations either
// way, SPEC 4.5). Every arm's workspace past the first is created after a
// product invocation: the two spec sources are staged-source records (S-9).
const T4_5_FILES = {
  "specs/A.mdx": stagedMdx(
    "T4-5 specs/A.mdx",
    '<S id="a">\nAlpha behavior.\n</S>\n\n<S id="b">\nBeta behavior.\n</S>\n',
  ),
  "specs/B.mdx": stagedMdx(
    "T4-5 specs/B.mdx",
    '<S id="x">\nOther behavior.\n</S>\n',
  ),
  "src/t.ts": "export const SPEC = 1;\n",
} as const;

// `text` bound by its own declaration — two declarations of one module
// binding distinct identifiers, valid under SPEC 4 — so that every arm's
// `text(SPEC.b)` is a spec module `text` call (4.3) whose argument chain is
// rooted at the collided identifier, whatever the pairing does to `SPEC`.
const T4_5_TEXT_IMPORT = 'import { text } from "../specs/A.xspec";';
const T4_5_MARKER_CHAIN = "SPEC.a";
const T4_5_TEXT_CALL = "text(SPEC.b)";

/** One pairing of a spec module import with a colliding import (SPEC 4.5). */
interface TypeOnlyCollisionPairing {
  /** Which pairing this is (failure diagnostics). */
  readonly name: string;
  /** The spec module import binding `SPEC` — value-level or type-only. */
  readonly spec: string;
  /** The other import binding `SPEC` — spec or non-spec, type-only or not. */
  readonly other: string;
}

// The four pairings (TEST-SPEC T4-5): the type-only exemption of SPEC 4.5
// reaches a chain the language roots at one binding, and a colliding
// identifier roots it at none — whether or not either import is type-only.
const T4_5_PAIRINGS: readonly TypeOnlyCollisionPairing[] = [
  {
    name: "a value-level spec import beside a type-only import of a second spec module",
    spec: 'import SPEC from "../specs/A.xspec";',
    other: 'import type SPEC from "../specs/B.xspec";',
  },
  {
    name: "a value-level spec import beside a type-only non-spec import",
    spec: 'import SPEC from "../specs/A.xspec";',
    other: 'import type { SPEC } from "./t";',
  },
  {
    name: "a type-only spec import beside a value-level non-spec import",
    spec: 'import type SPEC from "../specs/A.xspec";',
    other: 'import { SPEC } from "./t";',
  },
  {
    name: "a type-only spec import beside a type-only non-spec import",
    spec: 'import type SPEC from "../specs/A.xspec";',
    other: 'import type { SPEC } from "./t";',
  },
];

/** A staged `src/app.ts` for one arm and its constructs' byte positions. */
interface StagedTypeOnlyCollisionArm {
  /** The pairing and its declaration order (failure diagnostics). */
  readonly name: string;
  /** The whole file: `text` import, the pair, blank, marker, `text` call. */
  readonly source: string;
  /**
   * The two colliding import declarations' end-widened byte windows
   * (support.ts byteWindow), in file order — the `text` import is no
   * colliding declaration and lies in neither.
   */
  readonly collidingWindows: readonly {
    readonly start: number;
    readonly end: number;
  }[];
  /** The marker's bare chain, exactly (SPEC 14: terminator excluded). */
  readonly markerRange: { readonly start: number; readonly end: number };
  /** The `text(...)` call, callee through closing parenthesis, exactly (14). */
  readonly textCallRange: { readonly start: number; readonly end: number };
}

/**
 * Lay out an arm's `src/app.ts` — the `text` import, then the pairing's two
 * declarations in the given order, one per line, then the marker statement
 * and the `text(...)` call statement after a blank line — and fix every
 * construct's byte position from the exact bytes. The file is pure ASCII,
 * so string indices are byte offsets.
 */
function stageTypeOnlyCollisionArm(
  pairing: TypeOnlyCollisionPairing,
  order: "spec-first" | "other-first",
): StagedTypeOnlyCollisionArm {
  const declarations =
    order === "spec-first"
      ? [pairing.spec, pairing.other]
      : [pairing.other, pairing.spec];
  let prefix = `${T4_5_TEXT_IMPORT}\n`;
  const collidingWindows = declarations.map((declaration) => {
    const window = byteWindow(prefix, declaration);
    prefix += `${declaration}\n`;
    return window;
  });
  const markerPrefix = `${prefix}\n`;
  const textCallPrefix = `${markerPrefix}${T4_5_MARKER_CHAIN};\n`;
  const source = `${textCallPrefix}${T4_5_TEXT_CALL};\n`;
  const exact = (
    before: string,
    construct: string,
  ): { start: number; end: number } => {
    const start = Buffer.byteLength(before, "utf8");
    return { start, end: start + Buffer.byteLength(construct, "utf8") };
  };
  return {
    name: `${pairing.name} (${order === "spec-first" ? "the spec import declared first" : "the other import declared first"})`,
    source,
    collidingWindows,
    markerRange: exact(markerPrefix, T4_5_MARKER_CHAIN),
    textCallRange: exact(textCallPrefix, T4_5_TEXT_CALL),
  };
}

/** A finding's locations as JSON-safe `[file, start, end]` tuples (12.7 order). */
function t45LocationTuples(finding: Finding): readonly (readonly unknown[])[] {
  return finding.locations.map((location) => [
    location.file,
    location.range.start,
    location.range.end,
  ]);
}

/**
 * Assert a reference-spelling finding locates exactly one range — the span
 * its occurrence would occupy (SPEC 14, 5.7), byte-exact — in `src/app.ts`
 * and concerns no path (12.7).
 */
function assertT45SpellingFinding(
  finding: Finding,
  range: { readonly start: number; readonly end: number },
  context: string,
): void {
  assertFindingLocatesExactly(
    finding,
    [{ file: "src/app.ts", window: range }],
    context,
  );
  assertSameJson(
    t45LocationTuples(finding),
    [["src/app.ts", range.start, range.end]],
    `${context}: the one location is byte-exact — the spelling's own span, ` +
      `terminators and delimiters excluded (SPEC 14, 5.7, 1.7)`,
  );
}

/**
 * Assert the findings a T4-5 arm's workspace reports, in 12.7 order:
 * condition 7 for the marker chain, condition 7 for the `text(...)` call
 * (each byte-exact at the span its occurrence would occupy, SPEC 14), then
 * the one condition-15 collision locating both colliding import
 * declarations — each within its own byte window, the `text` import not
 * among them — and nothing else (14: every colliding declaration, no
 * representative chosen). Never the type-only exemption's silence (T4-4) —
 * no finding at all — nor an edge-recording resolution: both are what a
 * product rooting the chain at whichever binding TypeScript's own
 * resolution prefers exhibits instead (SPEC 2.4, 4.5).
 */
function assertTypeOnlyCollisionFindings(
  findings: readonly Finding[],
  staged: StagedTypeOnlyCollisionArm,
  context: string,
): void {
  assertSameJson(
    findings.map((finding) => finding.condition),
    ["14.7", "14.7", "14.15"],
    `${context}: exactly the two unresolved chains (condition 7, one per ` +
      `spelling) beside the one collision (condition 15), in 12.7 order — ` +
      `numbered conditions in numeric order, then by location; a colliding ` +
      `identifier roots no chain whether or not either import is type-only ` +
      `(SPEC 2.4, 4.5, 14.7, 14.15, 12.7) — never the type-only exemption's ` +
      `silence (T4-4)`,
  );
  assertT45SpellingFinding(
    findings[0]!,
    staged.markerRange,
    `${context}: the marker's 14.7 locates the bare reference chain, ` +
      `exclusive of the statement terminator (SPEC 14, 5.7)`,
  );
  assertT45SpellingFinding(
    findings[1]!,
    staged.textCallRange,
    `${context}: the \`text(...)\` call's 14.7 locates the call expression, ` +
      `callee through closing parenthesis (SPEC 14, 5.7)`,
  );
  assertFindingLocatesExactly(
    findings[2]!,
    staged.collidingWindows.map((window) => ({ file: "src/app.ts", window })),
    `${context}: the 14.15 locates both colliding import declarations, each ` +
      `by its own characters, and not the \`text\` import beside them ` +
      `(SPEC 14, 1.7, 2.1, 4)`,
  );
}

/**
 * An occurrence record's every datum (SPEC 5.7) as one JSON-safe tuple —
 * file, own range, kind, source (identity plus range, or the unavailability
 * marker), target — so whole records compare key-order-free.
 */
function t45OccurrenceTuple(record: OccurrenceRecord): readonly unknown[] {
  const source =
    "unavailable" in record.source
      ? "(source unavailable)"
      : [
          record.source.identity,
          record.source.range.start,
          record.source.range.end,
        ];
  return [
    record.file,
    record.range.start,
    record.range.end,
    record.kind,
    source,
    record.target,
  ];
}

/**
 * One arm: `build` and `check` report the collision beside condition 7 for
 * each chain, exit 1; and `occurrences --file src/app.ts`, answering on the
 * failing workspace (SPEC 11.2), carries those findings and lists no record
 * for the two spellings — a chain rooted at the collided identifier records
 * no edge and no occurrence (5.7, T5.7-4).
 */
async function assertTypeOnlyCollisionArm(
  product: ProductBinding,
  staged: StagedTypeOnlyCollisionArm,
): Promise<void> {
  await withWorkspace(
    SPEC_AND_CODE_CONFIG,
    { ...T4_5_FILES, "src/app.ts": staged.source },
    async (workspace) => {
      const buildContext = `T4-5 \`build --json\` over ${staged.name}`;
      assertTypeOnlyCollisionFindings(
        await buildFindings(product, workspace, buildContext),
        staged,
        buildContext,
      );

      // `check`: the same validation, exit 1 (SPEC 12.2). Staleness of the
      // never-built workspace's derived files is 14.10's own business —
      // set aside, the findings are exactly the arm's.
      const checkContext = `T4-5 \`check --json\` over ${staged.name}`;
      const checkResult = await expectExit(
        product,
        workspace,
        ["check", "--json"],
        1,
        `${checkContext} — \`check\` performs all build validations and ` +
          `exits 1 on the findings (SPEC 12.2, 2.4, 4.5)`,
      );
      assertTypeOnlyCollisionFindings(
        decodeFindingsReport(
          parseJsonStdout(checkResult, checkContext),
          checkContext,
        ).findings.filter((finding) => finding.condition !== "14.10"),
        staged,
        checkContext,
      );

      // `occurrences --file src/app.ts`, answering on the failing workspace
      // (SPEC 11.2): the code file's findings accompany (exit 1, the full
      // answer still emitted), and the record set is empty — the two chains
      // rooted at the collided identifier record no edge and no occurrence
      // (5.7); their positions reach consumers through the findings alone.
      const occContext = `T4-5 \`occurrences --file src/app.ts\` over ${staged.name}`;
      const occResult = await expectExit(
        product,
        workspace,
        ["occurrences", "--file", "src/app.ts"],
        1,
        `${occContext} — the answer carries the domain's findings, so exit ` +
          `1 with the full answer document (SPEC 11.2, 11.3)`,
      );
      const report = decodeOccurrencesReport(
        parseJsonStdout(
          occResult,
          `${occContext} — a single JSON document is the only output form ` +
            `(SPEC 11)`,
        ),
        occContext,
      );
      assertTypeOnlyCollisionFindings(
        report.findings,
        staged,
        `${occContext}: the code file's findings accompany the answer ` +
          `(SPEC 11.2, 11.3)`,
      );
      assertSameJson(
        report.occurrences.map(t45OccurrenceTuple),
        [],
        `${occContext}: no record for the marker or the \`text(...)\` call — ` +
          `a chain rooted at an identifier two imports bind, either type-only ` +
          `or not, records no edge and no occurrence, its position reported ` +
          `by its finding's range alone; never the type-only exemption's ` +
          `silence (SPEC 2.4, 4.5, 5.7, 11.2, T4-4)`,
      );
    },
  );
}

const T4_5 = defineProductTest({
  id: "T4-5",
  title:
    "type-only import collisions — an identifier a spec module import binds that another import also binds, either or both type-only (a second spec module's type-only default, a type-only non-spec binding, a value-level non-spec binding beside a type-only spec import, both type-only), staged in both declaration orders, roots no chain: `build` and `check` report 14.15 locating both declarations and 14.7 for the marker and the `text` call (exit 1), and `occurrences --file` on the failing workspace lists no record for them beside the findings — never the type-only exemption's silence (SPEC 2.4, 4, 4.5, 5.7, 11.2, 14.7, 14.15)",
  run: async (product) => {
    for (const pairing of T4_5_PAIRINGS) {
      for (const order of ["spec-first", "other-first"] as const) {
        await assertTypeOnlyCollisionArm(
          product,
          stageTypeOnlyCollisionArm(pairing, order),
        );
      }
    }
  },
});

/** TEST-SPEC §4 preamble, in canonical ID order (SUITE-12). */
export const section4Tests: readonly ProductTestEntry[] = [
  T4_1,
  T4_2,
  T4_3,
  T4_4,
  T4_5,
];
