// CONF-ORPHAN conformer fixture (CERTIFICATIONS.md §CONF-ORPHAN; TEST-SPEC 17
// C-1/C-2). A harness-owned executable product implementing §CONF-ORPHAN's
// Scope with the simplest conforming behavior — driven only through the C-2
// executable/workspace binding, never importing product code (the product and
// the harness are distinct programs; this fixture is part of the harness).
//
// Scope implemented (see CERTIFICATIONS.md §CONF-ORPHAN):
// - Workspaces of one configured spec group of trivial single-section `.mdx`
//   sources — an opening `<S id="…">` (or `<Spec …>`) line, plain Markdown
//   lines, and the matching closing tag as the last line: no imports,
//   embeddings, comments, or props beyond `id` — as T13.4-11 stages them;
//   `markdown` absent, `{ emit: false }`, or `{ emit: true }` emitting next to
//   sources or under an `outDir` (7.3); a code group (7.2) whose matches are
//   well-formed TypeScript of the `export const n = 1` form (14.20); no
//   `coverage`, `policy`, or git. Anything outside that shape — another
//   source form, another code form, a `coverage` or `policy` rule, another
//   command — is refused loudly with exit 70 (`xspec: fixture scope error:
//   …` on stderr), outside SPEC 12.0's exit partition: a fixture-side
//   condition, never a product verdict.
// - Command surface: `build` (12.1) and `check` (12.2), each with `--json`
//   and `--config` — neither mutating (13.5), so `--test-hold`, value-taking
//   by name all the same, is an unknown flag of both, the usage error of
//   12.0 — read under the invocation grammar of 12.0 (flag tokens
//   anywhere, a value-taking flag taking the whole next token, `--` ending
//   flag reading, arity fixed by name, a repeated flag, an unknown flag or
//   command, and a surplus operand usage errors; JSON output in effect
//   exactly when `--json` is read as a flag), with the configuration located
//   per 7 (upward search for `xspec.config.ts`, or `--config` resolved
//   against the working directory) and its errors reported per 14.14/12.7.
// - Contracts under certification: 13.4's removal of a recorded derived path
//   the current sources and configuration no longer generate — its occupant
//   judged at the path itself (lstat, never through a link); a directory or
//   a discovered source left as it is; anything else removed, a symbolic
//   link as the link itself, never its target; nothing read below a
//   workspace-relative directory component occupied by anything other than a
//   directory, a symbolic link included whatever it targets, the path then
//   holding nothing and its removal making no write — and 14.10's
//   recorded-file form, reporting exactly the occupants that removal would
//   remove. Both consult one function, `recordedOccupant`, so the report and
//   the removal cannot drift apart.
//
// Key mechanisms:
// - Discovery (7, 13.4): a walk of plain files under the workspace root that
//   never follows or discovers a symbolic link; byte-wise globs (`*`, `?`,
//   `**` as a whole segment, the dot-segment rule); the source exclusion of
//   13.4 (`.xspec.` names, `.xspec/` paths, and — while emission is enabled
//   — the configured Markdown emit destinations, by configuration alone);
//   14.19's path rules; a file in a spec and a code group a configuration
//   error (14.14).
// - `build` (12.1): validates (14.19, and 14.22 over its own write paths —
//   every derived path's workspace-relative directory components, and a
//   module or Markdown path that is a directory component of another write
//   path or of a discovered source's path); on findings exits 1 writing
//   nothing. Otherwise it writes each source's module `NAME.xspec.ts` (13.1;
//   content beyond the path is out of scope, so fixed bytes naming the
//   source; no companion is written) and, while emission is enabled, its
//   Markdown per 3 (13.2) — each write replacing its path's occupant (a
//   directory with everything it holds, a symbolic link as the link) and
//   creating missing directories, never writing through a link (13.4) —
//   then removes every recorded path no longer generated (13.4, through
//   `recordedOccupant`), and last writes graph data, `.xspec/graph.json`,
//   whose record lists the derived paths generated (13.3). Writes precede
//   removals, so a removal below a path a write replaced finds nothing
//   there (13.4's order independence), and graph data comes last, so a
//   regeneration stopped early leaves the previous record naming every
//   orphan it has not yet removed.
// - `check` (12.2): the same validations, then 14.10's forms — the per-file
//   form (each generated path's occupant judged itself: a plain file holding
//   exactly the generated bytes, or stale), the graph-data unit form
//   (missing, mismatching the current sources and configuration with the
//   record excluded, or unreadable as a record, 14.23 — one finding
//   concerning the graph-data area `.xspec`), the mismatch forms only on a
//   workspace passing `build`'s validations, and the recorded-file form on
//   any workspace whose record reads. Exits 1 on any finding.
// - Graph data is byte-deterministic for the workspace (12.0): the discovered
//   sources with their groups, content hashes, and sections, plus the
//   record — never history, so a regenerated workspace equals a twin built
//   fresh from the same sources and configuration (H-6).
//
// Determinism (SPEC 12.0): no wall clock, no randomness, no absolute paths in
// any output; paths in byte order; all JSON serialized with byte-sorted keys.
//
// Deviation seam: runXspec(argv, cwd, options) assigns `options` onto the
// module-level `deviations` switches (all off = this conformer). Each
// VIOL-ORPHAN-* violator is a bin-<name>.mjs passing exactly one switch,
// consumed where 13.4's removal resolves and removes a recorded path's
// occupant (`recordedOccupant`, `removeRecorded`):
// - `componentLinksInsideRoot` (VIOL-ORPHAN-THROUGHLINK, bin-throughlink.mjs):
//   `recordedOccupant` resolves a workspace-relative directory component
//   occupied by a symbolic link to a directory inside the workspace root
//   through that link, so the removal and 14.10's recorded-file form — both
//   consulting it, and nothing else — judge, report, and remove the entry the
//   link's target holds under the path's remaining components.
// - `removeLinkTarget` (VIOL-ORPHAN-LINKTARGET, bin-linktarget.mjs):
//   `removeRecorded`, given a removable occupant that is a symbolic link,
//   deletes the plain file the link resolves to (nothing where it resolves
//   to no plain file) and leaves the link standing; `recordedOccupant`, and
//   so 14.10's recorded-file form, is untouched, the link still judged as
//   itself, and `writeDerived` still replaces a link as the occupant.

import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";
import * as fsp from "node:fs/promises";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// Outcome carriers
// ---------------------------------------------------------------------------

/**
 * Usage or configuration error (SPEC 12.0 exit 2): message on stderr in both
 * output forms; with JSON output in effect the 12.7 error document is the
 * entire stdout. `code`/`path` are the error finding's stable code and
 * concerned path — set for a configuration error (14.14), `null` for a plain
 * usage error (12.7).
 */
class UsageError extends Error {
  constructor(message, { code = null, path = null } = {}) {
    super(message);
    this.code = code;
    this.path = path;
  }
}

/** Findings (SPEC 12.0 exit 1): the findings report on stdout. */
class FindingsError extends Error {
  constructor(findings) {
    super("findings");
    this.findings = findings;
  }
}

/**
 * An invocation or workspace outside this fixture's scope
 * (CERTIFICATIONS.md §CONF-ORPHAN) that a conforming product would answer:
 * refused loudly with exit 70, outside the 12.0 partition, so a test reaching
 * it fails on its exit-code assertion with the cause on stderr — never on a
 * fabricated answer.
 */
class ScopeError extends Error {}

// ---------------------------------------------------------------------------
// Canonical JSON (sorted keys, SPEC 12.0) and byte order
// ---------------------------------------------------------------------------

function sortKeysDeep(value) {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value !== null && typeof value === "object") {
    const sorted = {};
    for (const key of Object.keys(value).sort(compareBytes)) {
      sorted[key] = sortKeysDeep(value[key]);
    }
    return sorted;
  }
  return value;
}

function canonicalJson(value) {
  return JSON.stringify(sortKeysDeep(value), null, 2);
}

/** Byte-wise comparison of two strings' UTF-8 encodings (SPEC 12.0). */
function compareBytes(a, b) {
  return Buffer.compare(Buffer.from(a, "utf8"), Buffer.from(b, "utf8"));
}

function byteSorted(strings) {
  return [...strings].sort(compareBytes);
}

// ---------------------------------------------------------------------------
// Deviation switches (CERTIFICATIONS.md §VIOL-ORPHAN-*), all off in the
// conformer; assigned by runXspec from each violator entry's options.
// ---------------------------------------------------------------------------

let deviations = {};

// ---------------------------------------------------------------------------
// Invocation grammar (SPEC 12.0)
// ---------------------------------------------------------------------------

const REPLACEMENT_CHARACTER = String.fromCodePoint(0xfffd);
const LINE_SEPARATOR = String.fromCodePoint(0x2028);
const PARAGRAPH_SEPARATOR = String.fromCodePoint(0x2029);
const BYTE_ORDER_MARK = String.fromCodePoint(0xfeff);

/**
 * Every flag of every command with its arity, fixed by name (12.0): 1 for a
 * flag taking the whole next token as its value, 0 for one taking none. A
 * `--` token naming no flag of any command takes no value.
 */
const FLAG_ARITY = new Map([
  ["--json", 0],
  ["--preview", 0],
  ["--tree", 0],
  ["--text", 0],
  ["--check", 0],
  ["--unreferenced", 0],
  ["--config", 1],
  ["--test-hold", 1],
  ["--file", 1],
  ["--to", 1],
  ["--from", 1],
  ["--kinds", 1],
  ["--group", 1],
  ["--tag", 1],
  ["--coverage", 1],
  ["--base", 1],
  ["--strategy", 1],
  ["--name", 1],
  ["--status", 1],
  ["--note", 1],
]);

/** Every command of the product (12): only `build` and `check` are served. */
const PRODUCT_COMMANDS = new Set([
  "build",
  "check",
  "ids",
  "show",
  "coverage",
  "impact",
  "review",
  "query",
  "occurrences",
  "view",
  "at",
  "inventory",
  "rename",
  "move",
  "version",
]);

/**
 * The flags each served command accepts (12.0): the globals `--json` and
 * `--config` alone. Neither `build` nor `check` is a mutating command (13.5:
 * `rename`, `move`, and the mutating `review` subcommands), so `--test-hold`
 * is an unknown flag of both — still value-taking, its arity fixed by name in
 * `FLAG_ARITY`, so `build --test-hold --json` reads `--json` as its value and
 * leaves JSON out of effect (CERTIFICATIONS.md preamble, T13.5-1).
 */
const COMMAND_FLAGS = {
  build: new Set(["--json", "--config"]),
  check: new Set(["--json", "--config"]),
};

/**
 * An argument value is malformed when it is not valid UTF-8 or contains
 * U+FFFD (12.0); Node decodes argv lossily, an ill-formed byte arriving as
 * U+FFFD, so the one test covers both.
 */
function isMalformedValue(value) {
  return value.includes(REPLACEMENT_CHARACTER);
}

/**
 * Read the arguments under the grammar of 12.0. Returns the flags (name to
 * value, `true` for a flag taking none), the remaining non-flag tokens in
 * order, whether JSON output is in effect (`--json` read as a flag, even
 * when the arguments are themselves the error), and the first syntax-class
 * error met, if any.
 */
function readInvocation(argv) {
  const flags = new Map();
  const words = [];
  let json = false;
  let error = null;
  const note = (message) => {
    if (error === null) error = message;
  };
  let flagsEnded = false;
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!flagsEnded && token === "--") {
      flagsEnded = true;
      continue;
    }
    if (!flagsEnded && token.startsWith("--")) {
      if (token === "--json") json = true;
      if (flags.has(token)) {
        note(
          `repeated flag ${token}: a flag may be given at most once (SPEC 12.0)`,
        );
      }
      if (FLAG_ARITY.get(token) === 1) {
        if (i + 1 >= argv.length) {
          note(`flag ${token} lacks its value (SPEC 12.0)`);
          flags.set(token, true);
        } else {
          i += 1;
          const value = argv[i];
          if (isMalformedValue(value)) {
            note(
              `malformed value for ${token}: not valid UTF-8, or containing U+FFFD (SPEC 12.0)`,
            );
          }
          flags.set(token, value);
        }
      } else {
        if (!FLAG_ARITY.has(token)) note(`unknown flag ${token} (SPEC 12.0)`);
        flags.set(token, true);
      }
      continue;
    }
    if (isMalformedValue(token)) {
      note(
        "malformed argument: not valid UTF-8, or containing U+FFFD (SPEC 12.0)",
      );
    }
    words.push(token);
  }
  return { flags, words, json, error };
}

// ---------------------------------------------------------------------------
// Filesystem occupants (SPEC 13.4: judged at the path itself, never through
// a symbolic link)
// ---------------------------------------------------------------------------

/**
 * The kind of a path's occupant, read with lstat: "dir", "file", "symlink",
 * "other", or "absent". A path below a non-directory component reads as
 * absent (ENOTDIR); callers judging 13.4's components walk them first.
 */
async function lstatKind(absPath) {
  try {
    const stats = await fsp.lstat(absPath);
    if (stats.isDirectory()) return "dir";
    if (stats.isFile()) return "file";
    if (stats.isSymbolicLink()) return "symlink";
    return "other";
  } catch (error) {
    if (error.code === "ENOENT" || error.code === "ENOTDIR") return "absent";
    throw error;
  }
}

/** A workspace-relative path's absolute form under the root. */
function absUnder(rootAbs, rel) {
  return path.join(rootAbs, ...rel.split("/"));
}

/**
 * A plain workspace-relative path (1.5, 7.3): one or more non-empty
 * `/`-separated segments, none `.` or `..`.
 */
function isPlainRelativePath(value) {
  return (
    typeof value === "string" &&
    value !== "" &&
    value.split("/").every((s) => s !== "" && s !== "." && s !== "..")
  );
}

// ---------------------------------------------------------------------------
// Configuration (SPEC 7): location, declarative parse, validation
// ---------------------------------------------------------------------------

const CONFIG_NAME = "xspec.config.ts";

/**
 * The anchoring form of SPEC 11.6/14 for a path identified relative to the
 * invocation working directory: `/`-joined relative segments, `.` for the
 * working directory itself.
 */
function anchoringPath(cwd, absPath) {
  const rel = path.relative(path.resolve(cwd), absPath);
  if (rel === "") return ".";
  return rel.split(path.sep).join("/");
}

/**
 * Locate, read, parse, and validate the configuration (SPEC 7, 14.14). The
 * configuration file is the occupant of the path the upward search finds —
 * the nearest directory holding an entry named `xspec.config.ts`, whatever
 * occupies it — or the path `--config` names, read only when it is a plain
 * file. Every defect is one configuration error concerning that path in the
 * anchoring form; a `--config` path nothing occupies is reported as given,
 * and missing configuration with no `--config` as `.` (14).
 */
async function loadConfig(cwd, configFlag) {
  let configPath;
  if (configFlag !== undefined) {
    configPath = path.resolve(cwd, configFlag);
    if ((await lstatKind(configPath)) === "absent") {
      throw new UsageError(
        `configuration error: --config ${configFlag} names nothing (SPEC 7, 14.14)`,
        { code: "configuration-error", path: configFlag },
      );
    }
  } else {
    let dir = path.resolve(cwd);
    for (;;) {
      const candidate = path.join(dir, CONFIG_NAME);
      if ((await lstatKind(candidate)) !== "absent") {
        configPath = candidate;
        break;
      }
      const parent = path.dirname(dir);
      if (parent === dir) {
        throw new UsageError(
          `configuration error: no ${CONFIG_NAME} found by upward search from the working directory (SPEC 7, 14.14)`,
          { code: "configuration-error", path: "." },
        );
      }
      dir = parent;
    }
  }
  const concerned = anchoringPath(cwd, configPath);
  const configError = (what) =>
    new UsageError(
      `configuration error: ${concerned}: ${what} (SPEC 7, 14.14)`,
      {
        code: "configuration-error",
        path: concerned,
      },
    );
  if ((await lstatKind(configPath)) !== "file") {
    throw configError(
      "the configuration path holds something other than a plain file",
    );
  }
  const bytes = await fsp.readFile(configPath);
  if (bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
    throw configError("the file begins with a byte-order mark");
  }
  let text;
  try {
    text = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(
      bytes,
    );
  } catch {
    throw configError("the file is not valid UTF-8");
  }
  const data = parseConfigText(text, configError);
  return {
    ...validateConfig(data, configError),
    root: path.dirname(configPath),
    configError,
  };
}

/** ECMAScript whitespace and line terminators, between tokens (14.20). */
function isConfigSpace(c) {
  return (
    c === BYTE_ORDER_MARK ||
    c === LINE_SEPARATOR ||
    c === PARAGRAPH_SEPARATOR ||
    /^[\t\v\f \n\r\p{Zs}]$/u.test(c)
  );
}

function isLineTerminator(c) {
  return (
    c === "\n" ||
    c === "\r" ||
    c === LINE_SEPARATOR ||
    c === PARAGRAPH_SEPARATOR
  );
}

const WORD_PATTERN = /[A-Za-z_$][A-Za-z0-9_$]*/y;

/**
 * Tokens of the declarative configuration (SPEC 7): punctuators, identifier
 * words, and static string literals — whose value is the characters between
 * the delimiters exactly as spelled, no escape interpreted (2.4) — with
 * whitespace and comments contributing nothing.
 */
function tokenizeConfig(text, configError) {
  const tokens = [];
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    if (isConfigSpace(c)) {
      i += 1;
      continue;
    }
    if (c === "/" && text[i + 1] === "/") {
      i += 2;
      while (i < text.length && !isLineTerminator(text[i])) i += 1;
      continue;
    }
    if (c === "/" && text[i + 1] === "*") {
      const end = text.indexOf("*/", i + 2);
      if (end === -1) throw configError("an unterminated block comment");
      i = end + 2;
      continue;
    }
    if ("{}[](),:;".includes(c)) {
      tokens.push({ type: "punct", value: c });
      i += 1;
      continue;
    }
    if (c === '"' || c === "'") {
      let j = i + 1;
      while (j < text.length && text[j] !== c) {
        if (text[j] === "\n" || text[j] === "\r") {
          throw configError("a line break inside a string literal");
        }
        if (text[j] === "\\") {
          j += text[j + 1] === "\r" && text[j + 2] === "\n" ? 3 : 2;
        } else {
          j += 1;
        }
      }
      if (j >= text.length) throw configError("an unterminated string literal");
      tokens.push({ type: "string", value: text.slice(i + 1, j) });
      i = j + 1;
      continue;
    }
    WORD_PATTERN.lastIndex = i;
    const word = WORD_PATTERN.exec(text);
    if (word !== null) {
      tokens.push({ type: "word", value: word[0] });
      i += word[0].length;
      continue;
    }
    throw configError(
      `unexpected character at offset ${String(i)}: only the declarative form is admitted`,
    );
  }
  return tokens;
}

/**
 * Parse the declarative configuration (SPEC 7): exactly an import of
 * `defineConfig` from "xspec" (optionally aliased; no `type` or `defer`
 * modifier, no import attributes) and a default export of one call to that
 * binding whose sole argument is statically literal — object literals with
 * non-computed identifier or string-literal keys (a key repeated within one
 * object a configuration error), array literals, static string literals, and
 * `true`/`false`. Objects are returned as Maps, in spelling order.
 */
function parseConfigText(text, configError) {
  const tokens = tokenizeConfig(text, configError);
  let i = 0;
  const peekIs = (type, value) =>
    tokens[i] !== undefined &&
    tokens[i].type === type &&
    (value === undefined || tokens[i].value === value);
  const take = (type, value, what) => {
    if (!peekIs(type, value)) throw configError(`expected ${what}`);
    const token = tokens[i];
    i += 1;
    return token.value;
  };
  take("word", "import", "the import of defineConfig");
  take("punct", "{", '"{" in the import of defineConfig');
  take("word", "defineConfig", "the name defineConfig");
  let binding = "defineConfig";
  if (peekIs("word", "as")) {
    i += 1;
    binding = take("word", undefined, "the import's alias");
  }
  if (peekIs("punct", ",")) i += 1;
  take("punct", "}", '"}" in the import of defineConfig');
  take("word", "from", '"from"');
  take("string", "xspec", 'the module specifier "xspec"');
  if (peekIs("punct", ";")) i += 1;
  take("word", "export", "the default export");
  take("word", "default", '"default"');
  take("word", binding, `a call of ${binding}`);
  take("punct", "(", `"(" after ${binding}`);
  const parseValue = () => {
    if (peekIs("string")) return take("string", undefined, "a string");
    if (peekIs("word", "true") || peekIs("word", "false")) {
      return take("word", undefined, "a boolean") === "true";
    }
    if (peekIs("punct", "{")) {
      i += 1;
      const object = new Map();
      while (!peekIs("punct", "}")) {
        const key = peekIs("string")
          ? take("string", undefined, "a key")
          : take("word", undefined, "an object key");
        if (object.has(key)) {
          throw configError(`the key ${JSON.stringify(key)} is repeated`);
        }
        take("punct", ":", `":" after the key ${JSON.stringify(key)}`);
        object.set(key, parseValue());
        if (!peekIs("punct", ",")) break;
        i += 1;
      }
      take("punct", "}", '"}" closing an object literal');
      return object;
    }
    if (peekIs("punct", "[")) {
      i += 1;
      const array = [];
      while (!peekIs("punct", "]")) {
        array.push(parseValue());
        if (!peekIs("punct", ",")) break;
        i += 1;
      }
      take("punct", "]", '"]" closing an array literal');
      return array;
    }
    throw configError(
      "expected a static literal: an object, array, string, or boolean",
    );
  };
  const value = parseValue();
  if (peekIs("punct", ",")) i += 1;
  take("punct", ")", `")" closing the call of ${binding}`);
  if (peekIs("punct", ";")) i += 1;
  if (i !== tokens.length) {
    throw configError("content after the default export");
  }
  if (!(value instanceof Map)) {
    throw configError("defineConfig takes one object literal");
  }
  return value;
}

/**
 * Whether a glob lies outside the workspace root, decided by its spelling
 * alone (SPEC 7): a leading `/`, or a depth falling below zero — `..`
 * lowering it, `.`, an empty segment, and `**` leaving it, every other
 * segment raising it.
 */
function globOutsideRoot(glob) {
  if (glob.startsWith("/")) return true;
  let depth = 0;
  for (const segment of glob.split("/")) {
    if (segment === "..") {
      depth -= 1;
      if (depth < 0) return true;
    } else if (segment !== "." && segment !== "" && segment !== "**") {
      depth += 1;
    }
  }
  return false;
}

/** One group map (7.1, 7.2): named lists of globs, in configuration order. */
function validatedGroups(value, section, configError) {
  if (!(value instanceof Map)) {
    throw configError(`${section} must be an object literal of named groups`);
  }
  const groups = [];
  for (const [name, globs] of value) {
    if (name === "") throw configError(`an empty ${section} group name`);
    if (name.includes(REPLACEMENT_CHARACTER)) {
      throw configError(`a ${section} group name containing U+FFFD`);
    }
    if (!Array.isArray(globs) || globs.some((g) => typeof g !== "string")) {
      throw configError(
        `the ${section} group ${JSON.stringify(name)} must be a list of glob strings`,
      );
    }
    for (const glob of globs) {
      if (globOutsideRoot(glob)) {
        throw configError(
          `the glob ${JSON.stringify(glob)} lies outside the workspace root`,
        );
      }
    }
    groups.push({ name, globs });
  }
  return groups;
}

/**
 * Validate the parsed configuration (SPEC 7, 7.1–7.3): `specs` required;
 * `code` and `markdown` optional; unknown keys anywhere a configuration
 * error; `markdown.emit` a required boolean and `markdown.outDir` a plain
 * workspace-relative path outside the graph-data area. `coverage` and
 * `policy` are outside this fixture's scope unless empty (an empty list
 * equals omission, 7).
 */
function validateConfig(data, configError) {
  const known = ["specs", "code", "markdown", "coverage", "policy"];
  for (const key of data.keys()) {
    if (!known.includes(key)) {
      throw configError(`the key ${JSON.stringify(key)} is unknown`);
    }
  }
  for (const key of ["coverage", "policy"]) {
    const value = data.get(key);
    if (value !== undefined && !(Array.isArray(value) && value.length === 0)) {
      throw new ScopeError(
        `the configuration key ${key} is outside this fixture's scope (CERTIFICATIONS.md §CONF-ORPHAN: no coverage or policy)`,
      );
    }
  }
  if (!data.has("specs")) throw configError("`specs` is required");
  const specGroups = validatedGroups(data.get("specs"), "specs", configError);
  const codeGroups = data.has("code")
    ? validatedGroups(data.get("code"), "code", configError)
    : [];
  let emit = false;
  let outDir = null;
  if (data.has("markdown")) {
    const markdown = data.get("markdown");
    if (!(markdown instanceof Map)) {
      throw configError("`markdown` must be an object literal");
    }
    for (const key of markdown.keys()) {
      if (key !== "emit" && key !== "outDir") {
        throw configError(`the key markdown.${key} is unknown`);
      }
    }
    if (typeof markdown.get("emit") !== "boolean") {
      throw configError("markdown.emit is required and must be true or false");
    }
    emit = markdown.get("emit");
    if (markdown.has("outDir")) {
      const value = markdown.get("outDir");
      if (!isPlainRelativePath(value)) {
        throw configError(
          "markdown.outDir must be one or more non-empty segments, none . or .., with no leading /",
        );
      }
      if (value === ".xspec" || value.startsWith(".xspec/")) {
        throw configError("markdown.outDir lies in the graph-data area .xspec");
      }
      outDir = value;
    }
  }
  return { specGroups, codeGroups, emit, outDir };
}

// ---------------------------------------------------------------------------
// Discovery (SPEC 7, 13.4)
// ---------------------------------------------------------------------------

const DOT = 0x2e;
const STAR = 0x2a;
const QUESTION = 0x3f;

/** One pattern segment against one path segment, byte-wise (SPEC 7). */
function segmentMatches(pattern, name) {
  const p = Buffer.from(pattern, "utf8");
  const s = Buffer.from(name, "utf8");
  // A path segment beginning with `.` is matched only by a pattern segment
  // written with a leading `.` (SPEC 7).
  if (s[0] === DOT && p[0] !== DOT) return false;
  const match = (i, j) => {
    if (i === p.length) return j === s.length;
    if (p[i] === STAR) {
      for (let k = j; k <= s.length; k += 1) {
        if (match(i + 1, k)) return true;
      }
      return false;
    }
    if (j === s.length) return false;
    if (p[i] === QUESTION || p[i] === s[j]) return match(i + 1, j + 1);
    return false;
  };
  return match(0, 0);
}

/**
 * Glob matching (SPEC 7): `*` any possibly empty byte run within a segment,
 * `?` one byte, `**` — as a whole pattern segment only — any number of
 * whole segments including none (never a dot-initial one), every other
 * character a literal; `.`, `..`, and empty pattern segments match nothing,
 * since no discovered path carries such a segment.
 */
function globMatches(glob, rel) {
  const patterns = glob.split("/");
  const names = rel.split("/");
  const match = (i, j) => {
    if (i === patterns.length) return j === names.length;
    if (patterns[i] === "**") {
      if (match(i + 1, j)) return true;
      for (let k = j; k < names.length; k += 1) {
        if (names[k].startsWith(".")) return false;
        if (match(i + 1, k + 1)) return true;
      }
      return false;
    }
    if (j === names.length) return false;
    return segmentMatches(patterns[i], names[j]) && match(i + 1, j + 1);
  };
  return match(0, 0);
}

/**
 * Every plain file under the root, workspace-relative (the directory-entry
 * names descending from the root, `/`-joined). A symbolic link — to a file
 * or a directory, broken or not — is never discovered and never traversed,
 * and no other non-plain kind is a source (SPEC 7).
 */
async function walkPlainFiles(rootAbs) {
  const files = [];
  const walk = async (dirAbs, prefix) => {
    const entries = await fsp.readdir(dirAbs, { withFileTypes: true });
    for (const entry of entries) {
      const rel = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
      if (entry.isDirectory()) {
        await walk(path.join(dirAbs, entry.name), rel);
      } else if (entry.isFile()) {
        files.push(rel);
      }
    }
  };
  await walk(rootAbs, "");
  return byteSorted(files);
}

/** A spec source's generated module path (13.1). */
function modulePathOf(sourceRel) {
  return `${sourceRel.slice(0, -".mdx".length)}.xspec.ts`;
}

/** A spec source's Markdown emit destination (13.2, 7.3). */
function markdownPathOf(config, sourceRel) {
  const emitted = `${sourceRel.slice(0, -".mdx".length)}.md`;
  return config.outDir === null ? emitted : `${config.outDir}/${emitted}`;
}

/**
 * Discover the configured sources (SPEC 7, 13.4): plain files matched by a
 * group's globs, less the derived files — names containing `.xspec.`, paths
 * under `.xspec/`, and, while emission is enabled, the configured Markdown
 * emit destinations of the discovered `.mdx` spec sources (7.3), which exist
 * by configuration alone. A file in both a spec and a code group is a
 * configuration error (7.2, 14.14).
 */
async function discover(config) {
  const groupsMatching = (groups, rel) =>
    groups
      .filter((group) => group.globs.some((glob) => globMatches(glob, rel)))
      .map((group) => group.name);
  const specMatches = [];
  const codeMatches = [];
  for (const rel of await walkPlainFiles(config.root)) {
    const name = rel.slice(rel.lastIndexOf("/") + 1);
    if (name.includes(".xspec.") || rel.startsWith(".xspec/")) continue;
    const specGroups = groupsMatching(config.specGroups, rel);
    const codeGroups = groupsMatching(config.codeGroups, rel);
    if (specGroups.length > 0) specMatches.push({ rel, groups: specGroups });
    if (codeGroups.length > 0) codeMatches.push({ rel, groups: codeGroups });
  }
  const emitDestinations = new Set();
  if (config.emit) {
    for (const match of specMatches) {
      if (match.rel.endsWith(".mdx")) {
        emitDestinations.add(markdownPathOf(config, match.rel));
      }
    }
  }
  const specSources = specMatches.filter((m) => !emitDestinations.has(m.rel));
  const codeSources = codeMatches.filter((m) => !emitDestinations.has(m.rel));
  const specPaths = new Set(specSources.map((m) => m.rel));
  const both = codeSources.find((m) => specPaths.has(m.rel));
  if (both !== undefined) {
    throw config.configError(
      `${both.rel} is matched by both a spec group and a code group`,
    );
  }
  return {
    specSources,
    codeSources,
    discovered: new Set([...specPaths, ...codeSources.map((m) => m.rel)]),
  };
}

// ---------------------------------------------------------------------------
// Sources in scope: trivial single-section `.mdx`, and `export const` code
// ---------------------------------------------------------------------------

/**
 * SPEC 3's line model: a terminator is CRLF, a lone LF, or a lone CR; the
 * final line may have none.
 */
function splitLines(text) {
  const lines = [];
  let start = 0;
  for (const match of text.matchAll(/\r\n|\n|\r/g)) {
    lines.push({ text: text.slice(start, match.index), terminator: match[0] });
    start = match.index + match[0].length;
  }
  if (start < text.length) {
    lines.push({ text: text.slice(start), terminator: "" });
  }
  return lines;
}

/** A source's bytes as text: valid UTF-8 with no byte-order mark (1.6). */
function sourceText(rel, bytes) {
  if (bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
    throw new ScopeError(
      `${rel} begins with a byte-order mark: an unparseable source (14.20) is outside this fixture's scope`,
    );
  }
  try {
    return new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(
      bytes,
    );
  } catch {
    throw new ScopeError(
      `${rel} is not valid UTF-8: an unparseable source (14.20) is outside this fixture's scope`,
    );
  }
}

/** An ID segment in this fixture's scope: a subset of 1.4's valid ones. */
function isScopeSegment(id) {
  return (
    /^[A-Za-z][A-Za-z0-9_-]*$/.test(id) &&
    !["then", "constructor", "prototype"].includes(id)
  );
}

/**
 * The scope's spec source shape: `<S id="X">` (or `<Spec id="X">`) alone on
 * the first line, plain Markdown lines, and the matching closing tag alone
 * on the last line. Returns the section's ID, its source range (1.7: the
 * construct from its opening tag's first byte through its closing tag's
 * last), and the compiled Markdown (3): the tag lines, left empty by the
 * tags' removal, dropped with their terminators, every other line kept.
 */
function parseTrivialSection(rel, bytes) {
  const text = sourceText(rel, bytes);
  const lines = splitLines(text);
  const outOfScope = (why) =>
    new ScopeError(
      `${rel}: ${why} — this fixture's sources are trivial single-section .mdx files (CERTIFICATIONS.md §CONF-ORPHAN)`,
    );
  const open =
    lines.length >= 2 ? /^<(S|Spec) id="([^"]*)">$/.exec(lines[0].text) : null;
  if (open === null) throw outOfScope("no opening tag alone on the first line");
  const last = lines[lines.length - 1];
  if (last.text !== `</${open[1]}>`) {
    throw outOfScope("no matching closing tag alone on the last line");
  }
  if (!isScopeSegment(open[2])) throw outOfScope(`the ID ${open[2]}`);
  const body = lines.slice(1, -1);
  for (const line of body) {
    if (/[<>{}]/.test(line.text) || /^\s*(import|export)\b/.test(line.text)) {
      throw outOfScope(`a construct beyond plain Markdown: ${line.text}`);
    }
  }
  return {
    id: open[2],
    range: {
      start: 0,
      end: Buffer.byteLength(
        text.slice(0, text.length - last.terminator.length),
        "utf8",
      ),
    },
    markdown: body.map((line) => line.text + line.terminator).join(""),
  };
}

/**
 * The scope's code source shape: well-formed TypeScript (14.20) of
 * `export const NAME = DIGITS` statements, one per line, optionally
 * terminated by `;`, blank lines between — no leading-zero decimal, which
 * TypeScript rejects. Anything else is outside this fixture's scope.
 */
function checkTrivialCode(rel, bytes) {
  const text = sourceText(rel, bytes);
  for (const line of splitLines(text)) {
    if (/^[\t ]*$/.test(line.text)) continue;
    if (
      !/^[\t ]*export[\t ]+const[\t ]+[A-Za-z_$][A-Za-z0-9_$]*[\t ]*=[\t ]*(0|[1-9][0-9]*)[\t ]*;?[\t ]*$/.test(
        line.text,
      )
    ) {
      throw new ScopeError(
        `${rel}: ${JSON.stringify(line.text)} — this fixture's code sources are \`export const n = 1\` statements (CERTIFICATIONS.md §CONF-ORPHAN)`,
      );
    }
  }
}

function sha256Hex(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

/** The fixed module bytes: content beyond the path is out of scope (13.1). */
function moduleContent(sourceRel) {
  return Buffer.from(
    `// Generated by xspec from ${sourceRel} (CONF-ORPHAN fixture: module content beyond its path is out of scope).\nexport {};\n`,
    "utf8",
  );
}

// ---------------------------------------------------------------------------
// Findings (SPEC 14, 12.7)
// ---------------------------------------------------------------------------

const CODE_TOKENS = new Map([
  [10, "stale-output"],
  [19, "invalid-source-path"],
  [22, "obstructed-write-path"],
]);

function finding(condition, concerned, message) {
  return { condition, path: concerned, message };
}

/**
 * The pinned findings order (12.7): by code — the numbered conditions in
 * numeric order — then locations (empty for every condition here), then
 * concerned path bytes, then identities (empty), then message; identical
 * findings collapse to one.
 */
function compareFindings(a, b) {
  if (a.condition !== b.condition) return a.condition - b.condition;
  const byPath = compareBytes(a.path, b.path);
  if (byPath !== 0) return byPath;
  return compareBytes(a.message, b.message);
}

function findingsDoc(findings) {
  const sorted = [...findings].sort(compareFindings);
  const collapsed = sorted.filter(
    (f, i) => i === 0 || compareFindings(sorted[i - 1], f) !== 0,
  );
  return {
    findings: collapsed.map((f) => ({
      code: CODE_TOKENS.get(f.condition),
      message: f.message,
      locations: [],
      path: f.path,
      identities: [],
    })),
  };
}

function emitReport(io, json, findings) {
  const doc = findingsDoc(findings);
  if (json) {
    io.stdout(`${canonicalJson(doc)}\n`);
  } else {
    for (const f of doc.findings) {
      io.stdout(`${f.path}: ${f.code}: ${f.message}\n`);
    }
  }
}

// ---------------------------------------------------------------------------
// The workspace model: sources, derived files, graph data
// ---------------------------------------------------------------------------

const GRAPH_DATA_AREA = ".xspec";
// The fixture's graph-data layout, unenumerated to consumers (13.3).
const GRAPH_DATA_FILE = ".xspec/graph.json";

/** Characters 7.1 bars from a spec source's path, beside `#` and U+FFFD. */
const SPEC_PATH_BARRED = [
  '"',
  "'",
  "\\",
  "\n",
  "\r",
  LINE_SEPARATOR,
  PARAGRAPH_SEPARATOR,
];

/**
 * Discover, validate, and analyze the workspace: the 14.19 findings, the
 * derived files the current sources and configuration generate (each
 * `.mdx` spec source's module and, while emission is enabled, its
 * Markdown), and the graph as graph data holds it.
 */
async function loadWorkspace(config) {
  const discovery = await discover(config);
  const findings = [];
  const derived = [];
  const sources = [];
  for (const source of discovery.specSources) {
    const rel = source.rel;
    if (!rel.endsWith(".mdx")) {
      findings.push(
        finding(
          19,
          rel,
          `${rel} is in a spec group without the .mdx extension; rename it or narrow the group's globs (SPEC 7.1)`,
        ),
      );
      continue;
    }
    if (
      [REPLACEMENT_CHARACTER, "#", ...SPEC_PATH_BARRED].some((c) =>
        rel.includes(c),
      )
    ) {
      findings.push(
        finding(
          19,
          rel,
          `${rel} contains a character a spec source's path may not hold; rename it (SPEC 7, 7.1)`,
        ),
      );
    }
    const bytes = await fsp.readFile(absUnder(config.root, rel));
    const section = parseTrivialSection(rel, bytes);
    derived.push({ rel: modulePathOf(rel), content: moduleContent(rel) });
    if (config.emit) {
      derived.push({
        rel: markdownPathOf(config, rel),
        content: Buffer.from(section.markdown, "utf8"),
      });
    }
    sources.push({
      path: rel,
      kind: "spec",
      groups: source.groups,
      hash: sha256Hex(bytes),
      sections: [{ id: section.id, range: section.range }],
    });
  }
  for (const source of discovery.codeSources) {
    const rel = source.rel;
    if ([REPLACEMENT_CHARACTER, "#"].some((c) => rel.includes(c))) {
      findings.push(
        finding(
          19,
          rel,
          `${rel} contains a character a source's path may not hold; rename it (SPEC 7)`,
        ),
      );
    }
    const bytes = await fsp.readFile(absUnder(config.root, rel));
    checkTrivialCode(rel, bytes);
    sources.push({
      path: rel,
      kind: "code",
      groups: source.groups,
      hash: sha256Hex(bytes),
    });
  }
  derived.sort((a, b) => compareBytes(a.rel, b.rel));
  sources.sort((a, b) => compareBytes(a.path, b.path));
  return {
    findings,
    derived,
    generated: new Set(derived.map((d) => d.rel)),
    discovered: discovery.discovered,
    graph: { sources },
  };
}

/**
 * 14.22 over `build`'s write paths (the derived files generated and graph
 * data), as `build` and `check` alike judge them: each workspace-relative
 * directory component occupied by anything other than a directory, and each
 * module or Markdown path that is a directory component of another write
 * path or of a discovered source's path — one finding per offending path.
 */
async function obstructionFindings(config, ws) {
  const writePaths = [...ws.derived.map((d) => d.rel), GRAPH_DATA_FILE];
  const offending = new Set();
  for (const rel of writePaths) {
    const segments = rel.split("/");
    for (let i = 1; i < segments.length; i += 1) {
      const component = segments.slice(0, i).join("/");
      const kind = await lstatKind(absUnder(config.root, component));
      if (kind === "absent") break;
      if (kind !== "dir") {
        offending.add(component);
        break;
      }
    }
  }
  const others = [...writePaths, ...ws.discovered];
  for (const item of ws.derived) {
    if (others.some((o) => o.startsWith(`${item.rel}/`))) {
      offending.add(item.rel);
    }
  }
  return [...offending].map((rel) =>
    finding(
      22,
      rel,
      `${rel} obstructs a path xspec writes: a directory component must be a directory, and a derived path no other write's or source's directory; move or delete what occupies it (SPEC 13.4)`,
    ),
  );
}

/** Graph data's bytes: the graph and the record of the paths generated. */
function graphDataBytes(ws) {
  return Buffer.from(
    `${canonicalJson({ derivedFiles: byteSorted(ws.generated), graph: ws.graph })}\n`,
    "utf8",
  );
}

/**
 * The recorded generation state (13.3, 14.23): "empty" where none exists —
 * the area absent, or a directory holding no graph data; "unreadable" where
 * state exists that cannot be read as a record — the area's own path held
 * by a non-directory, graph data that is no plain file, refuses its read,
 * or does not decode; "readable" otherwise, with the recorded paths and the
 * stored graph.
 */
async function readRecord(config) {
  const areaKind = await lstatKind(absUnder(config.root, GRAPH_DATA_AREA));
  if (areaKind === "absent") return { state: "empty", paths: [], graph: null };
  if (areaKind !== "dir") return { state: "unreadable" };
  const fileAbs = absUnder(config.root, GRAPH_DATA_FILE);
  const fileKind = await lstatKind(fileAbs);
  if (fileKind === "absent") return { state: "empty", paths: [], graph: null };
  if (fileKind !== "file") return { state: "unreadable" };
  let doc;
  try {
    doc = JSON.parse(
      new TextDecoder("utf-8", { fatal: true }).decode(
        await fsp.readFile(fileAbs),
      ),
    );
  } catch {
    return { state: "unreadable" };
  }
  if (
    doc === null ||
    typeof doc !== "object" ||
    !Array.isArray(doc.derivedFiles) ||
    !doc.derivedFiles.every(isPlainRelativePath) ||
    doc.graph === undefined
  ) {
    return { state: "unreadable" };
  }
  return { state: "readable", paths: doc.derivedFiles, graph: doc.graph };
}

// ---------------------------------------------------------------------------
// 13.4's removal of recorded paths no longer generated, and its report
// ---------------------------------------------------------------------------

/**
 * The occupant 13.4's removal judges for a recorded path: the path's
 * workspace-relative directory components are walked from the root, and
 * below a component that is absent or occupied by anything other than a
 * directory — a symbolic link included, whatever it targets — nothing is
 * read: the path holds nothing. Otherwise the occupant is the path's own,
 * judged itself (lstat, never through a link). Returns its kind and where
 * it stands.
 */
async function recordedOccupant(config, rel) {
  if (deviations.componentLinksInsideRoot) {
    return recordedOccupantThroughInsideLinks(config, rel);
  }
  const segments = rel.split("/");
  for (let i = 1; i < segments.length; i += 1) {
    const component = segments.slice(0, i).join("/");
    if ((await lstatKind(absUnder(config.root, component))) !== "dir") {
      return { kind: "absent", abs: null };
    }
  }
  const abs = absUnder(config.root, rel);
  return { kind: await lstatKind(abs), abs };
}

/**
 * VIOL-ORPHAN-THROUGHLINK's deviation (CERTIFICATIONS.md
 * §VIOL-ORPHAN-THROUGHLINK) — `recordedOccupant` with one clause of 13.4's
 * removal rule dropped: a workspace-relative directory component occupied by
 * a symbolic link to a directory inside the workspace root is resolved
 * through the link, and below it the occupant is the entry the link's target
 * holds under the path's remaining components, judged itself (lstat) as if
 * it stood at the recorded path. Unchanged: a component that is absent, a
 * plain file, or a symbolic link to anything else — a directory outside the
 * root, a file, nothing — still leaves the path holding nothing, nothing
 * read below it; and the occupant at the recorded path itself is still
 * judged as itself, a symbolic link there never followed.
 */
async function recordedOccupantThroughInsideLinks(config, rel) {
  const rootReal = await fsp.realpath(config.root);
  const segments = rel.split("/");
  let dirAbs = config.root;
  for (const segment of segments.slice(0, -1)) {
    const componentAbs = path.join(dirAbs, segment);
    const kind = await lstatKind(componentAbs);
    if (kind === "dir") {
      dirAbs = componentAbs;
      continue;
    }
    const targetAbs =
      kind === "symlink"
        ? await linkedDirectoryInsideRoot(componentAbs, rootReal)
        : null;
    if (targetAbs === null) return { kind: "absent", abs: null };
    dirAbs = targetAbs;
  }
  const abs = path.join(dirAbs, segments[segments.length - 1]);
  return { kind: await lstatKind(abs), abs };
}

/**
 * The directory a symbolic link resolves to, where that is a directory
 * inside the workspace root (the root's real path or below it); `null` for
 * a link resolving to anything else, outside the root, or nowhere (dangling
 * or looping).
 */
async function linkedDirectoryInsideRoot(linkAbs, rootReal) {
  let resolved;
  try {
    resolved = await fsp.realpath(linkAbs);
  } catch (error) {
    if (["ENOENT", "ENOTDIR", "ELOOP"].includes(error.code)) return null;
    throw error;
  }
  if ((await lstatKind(resolved)) !== "dir") return null;
  const fromRoot = path.relative(rootReal, resolved);
  const outside =
    fromRoot === ".." ||
    fromRoot.startsWith(`..${path.sep}`) ||
    path.isAbsolute(fromRoot);
  return outside ? null : resolved;
}

/**
 * Whether the removal removes the occupant (13.4): anything but a directory
 * or a discovered source; a path holding nothing is left as it is.
 */
function isRemovable(occupant, rel, ws) {
  return (
    occupant.kind !== "absent" &&
    occupant.kind !== "dir" &&
    !ws.discovered.has(rel)
  );
}

/**
 * Remove a recorded path no longer generated (13.4): its occupant, where
 * removable, unlinked — a symbolic link as the link itself, never its
 * target; anything else left as it is, the removal making no write.
 */
async function removeRecorded(config, rel, ws) {
  const occupant = await recordedOccupant(config, rel);
  if (!isRemovable(occupant, rel, ws)) return;
  if (deviations.removeLinkTarget && occupant.kind === "symlink") {
    await removeLinkedPlainFile(occupant.abs);
    return;
  }
  await fsp.unlink(occupant.abs);
}

/**
 * VIOL-ORPHAN-LINKTARGET's deviation (CERTIFICATIONS.md
 * §VIOL-ORPHAN-LINKTARGET) — `removeRecorded` with one clause of 13.4's
 * removal rule inverted: where the recorded path's occupant is a symbolic
 * link, the removal deletes in place of the link the plain file the link
 * resolves to — nothing where it resolves to no plain file (dangling,
 * looping, or reaching a directory or another kind) — and leaves the link
 * standing. The occupant is still judged as itself by `recordedOccupant`,
 * so 14.10's recorded-file form is unchanged; nothing is read below a
 * non-directory component; derived-file writes (`writeDerived`) still
 * replace a link as the occupant.
 */
async function removeLinkedPlainFile(linkAbs) {
  let resolved;
  try {
    resolved = await fsp.realpath(linkAbs);
  } catch (error) {
    if (["ENOENT", "ENOTDIR", "ELOOP"].includes(error.code)) return;
    throw error;
  }
  if ((await lstatKind(resolved)) !== "file") return;
  await fsp.unlink(resolved);
}

/**
 * Write one derived file (13.4): the path's occupant is replaced — a
 * directory with everything it holds, a symbolic link as the link itself —
 * missing directories are created, and nothing is written through a link
 * (the exclusive create fails rather than follow anything left there).
 */
async function writeDerived(config, rel, content) {
  const abs = absUnder(config.root, rel);
  const kind = await lstatKind(abs);
  if (kind === "dir") {
    await fsp.rm(abs, { recursive: true, force: true });
  } else if (kind !== "absent") {
    await fsp.unlink(abs);
  }
  await fsp.mkdir(path.dirname(abs), { recursive: true });
  await fsp.writeFile(abs, content, { flag: "wx" });
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/**
 * `xspec build` (12.1): on validation findings (14.19, 14.22) exit 1,
 * modifying nothing; otherwise write every derived file, remove the
 * recorded paths no longer generated (13.4; an unreadable or empty record
 * names none — such orphans lie outside xspec's knowledge), then write
 * graph data recording the paths generated (13.3).
 */
async function commandBuild(io, cwd, configFlag, json) {
  const config = await loadConfig(cwd, configFlag);
  const ws = await loadWorkspace(config);
  const findings = [...ws.findings, ...(await obstructionFindings(config, ws))];
  if (findings.length > 0) throw new FindingsError(findings);
  const record = await readRecord(config);
  for (const item of ws.derived) {
    await writeDerived(config, item.rel, item.content);
  }
  if (record.state === "readable") {
    for (const rel of byteSorted(new Set(record.paths))) {
      if (!ws.generated.has(rel)) await removeRecorded(config, rel, ws);
    }
  }
  await writeDerived(config, GRAPH_DATA_FILE, graphDataBytes(ws));
  if (json) emitReport(io, true, []);
  return 0;
}

/**
 * `xspec check` (12.2): the build validations, then 14.10's forms — per
 * file and graph data (mismatch forms) on a workspace passing them, the
 * unreadable-record unit form and the recorded-file form on any workspace.
 * Writes nothing; exits 1 on any finding.
 */
async function commandCheck(io, cwd, configFlag, json) {
  const config = await loadConfig(cwd, configFlag);
  const ws = await loadWorkspace(config);
  const findings = [...ws.findings, ...(await obstructionFindings(config, ws))];
  const passing = findings.length === 0;
  const record = await readRecord(config);
  if (record.state === "unreadable") {
    findings.push(
      finding(
        10,
        GRAPH_DATA_AREA,
        "the recorded generation state under .xspec cannot be read as a record; run `xspec build` to replace it (SPEC 14.10, 14.23)",
      ),
    );
  } else if (
    passing &&
    (record.graph === null ||
      canonicalJson(record.graph) !== canonicalJson(ws.graph))
  ) {
    findings.push(
      finding(
        10,
        GRAPH_DATA_AREA,
        "graph data is missing or does not match the current sources and configuration; run `xspec build` (SPEC 14.10, 13.3)",
      ),
    );
  }
  if (passing) {
    for (const item of ws.derived) {
      const abs = absUnder(config.root, item.rel);
      const current =
        (await lstatKind(abs)) === "file" &&
        Buffer.compare(await fsp.readFile(abs), item.content) === 0;
      if (!current) {
        findings.push(
          finding(
            10,
            item.rel,
            `${item.rel} is missing or does not match what the current sources and configuration generate; run \`xspec build\` (SPEC 14.10)`,
          ),
        );
      }
    }
  }
  if (record.state === "readable") {
    const writePaths = [...ws.generated, GRAPH_DATA_FILE];
    for (const rel of new Set(record.paths)) {
      if (ws.generated.has(rel)) continue;
      if (!isRemovable(await recordedOccupant(config, rel), rel, ws)) continue;
      const obstructs = writePaths.some((w) => w.startsWith(`${rel}/`));
      findings.push(
        finding(
          10,
          rel,
          obstructs
            ? `${rel} is a recorded derived file no longer generated that obstructs a path the rebuild writes; delete it manually, then run \`xspec build\` (SPEC 14.10, 13.4)`
            : `${rel} is a recorded derived file the current sources and configuration no longer generate; run \`xspec build\` to remove it (SPEC 14.10, 13.4)`,
        ),
      );
    }
  }
  if (findings.length > 0) throw new FindingsError(findings);
  if (json) emitReport(io, true, []);
  return 0;
}

// ---------------------------------------------------------------------------
// Entry and dispatch (SPEC 12.0 exit partition)
// ---------------------------------------------------------------------------

/**
 * Run one invocation: `argv` without the executable, `cwd` the working
 * directory, `options` the deviation switches (none for this conformer).
 * Returns the exit code.
 */
export async function runXspec(argv, cwd, options = {}) {
  deviations = { ...options };
  const io = {
    stdout: (text) => process.stdout.write(text),
    stderr: (text) => process.stderr.write(text),
  };
  let json = false;
  try {
    const invocation = readInvocation(argv);
    json = invocation.json;
    if (invocation.error !== null) throw new UsageError(invocation.error);
    const [command, ...operands] = invocation.words;
    if (command === undefined) {
      throw new UsageError("expected a command (SPEC 12.0)");
    }
    if (!PRODUCT_COMMANDS.has(command)) {
      throw new UsageError(`unknown command ${command} (SPEC 12.0)`);
    }
    const accepted = COMMAND_FLAGS[command];
    if (accepted === undefined) {
      throw new ScopeError(
        `the ${command} command is outside this fixture's surface: build and check alone (CERTIFICATIONS.md §CONF-ORPHAN)`,
      );
    }
    for (const name of invocation.flags.keys()) {
      if (!accepted.has(name)) {
        throw new UsageError(`unknown flag ${name} for ${command} (SPEC 12.0)`);
      }
    }
    if (operands.length > 0) {
      throw new UsageError(
        `surplus operand ${operands[0]}: ${command} takes no operands (SPEC 12.0)`,
      );
    }
    const configFlag = invocation.flags.get("--config");
    return command === "build"
      ? await commandBuild(io, cwd, configFlag, json)
      : await commandCheck(io, cwd, configFlag, json);
  } catch (error) {
    if (error instanceof UsageError) {
      // Usage and configuration errors (12.0): the message on stderr in both
      // output forms; with JSON output in effect the 12.7 error document is
      // the entire stdout, and without it stdout stays empty.
      if (json) {
        io.stdout(
          `${canonicalJson({
            error: {
              code: error.code,
              message: error.message,
              locations: [],
              path: error.path,
              identities: [],
            },
          })}\n`,
        );
      }
      io.stderr(`xspec: ${error.message}\n`);
      return 2;
    }
    if (error instanceof FindingsError) {
      emitReport(io, json, error.findings);
      return 1;
    }
    if (error instanceof ScopeError) {
      io.stderr(`xspec: fixture scope error: ${error.message}\n`);
      return 70;
    }
    // A crash is a fixture bug: exit outside the 12.0 partition so every
    // exit-code assertion fails loudly and the diagnosis carries the stack.
    io.stderr(
      `xspec: internal fixture error: ${error?.stack ?? String(error)}\n`,
    );
    return 70;
  }
}
